---
title: "chimeric"
output: html_notebook
---
```{r}
library(Seurat)
library(dittoSeq)
library(harmony)
library(SeuratWrappers)
library(scCustomize)
library(presto)
library(viridis)
library(stringr)
library(FastCAR)
library(Matrix)
library(DropletQC)
library(SingleCellExperiment)
library(dreamlet)
library(plot1cell)

ReadSTAR <- function(data.dir, vireo,  proj = "SeuratObject", feats = 1000, 
                     counts = 1000, sample="Sample") {
  data.dir.genefull = paste0(data.dir, "GeneFull_Ex50pAS/raw")
  mtx = file.path(data.dir.genefull, "UniqueAndMult-EM.mtx")
  cells = file.path(data.dir.genefull, "barcodes.tsv")
  features = file.path(data.dir.genefull, "features.tsv")
  raw = ReadMtx(mtx = mtx, cells = cells, features = features)
  
  seurat = CreateSeuratObject(raw, project=proj, min.features = feats)
  
  data.dir.velo = paste0(data.dir, "/Velocyto/raw")
  cells = file.path(data.dir.velo, "barcodes.tsv")
  features = file.path(data.dir.velo, "features.tsv")
  spliced = file.path(data.dir.velo, "spliced.mtx")
  unspliced = file.path(data.dir.velo, "unspliced.mtx")
  ambi = file.path(data.dir.velo, "ambiguous.mtx")
  spliced = ReadMtx(mtx = spliced, cells = cells, features = features)
  unspliced = ReadMtx(mtx = unspliced, cells = cells, features = features)
  ambi = ReadMtx(mtx = ambi, cells = cells, features = features)
  spliced = spliced + ambi

  seurat[['unspliced']] = CreateAssayObject(unspliced[,colnames(seurat)])
  seurat[['spliced']] = CreateAssayObject(spliced[,colnames(seurat)])
  seurat$Sample = sample
  
  vir = read.table(paste0(vireo, "donor_ids.tsv"), sep='\t', 
                     header=T, row.names = 1)
  cbc = intersect(rownames(vir), colnames(seurat))
  seurat = subset(seurat, cells=cbc)
  vir = vir[cbc,]
  seurat@meta.data = cbind(seurat@meta.data, vir)
  seurat = subset(seurat, subset=donor_id != "unassigned")

  ambProfile = describe.ambient.RNA.sequence(fullMatrix = raw, 
                                             start = 10, 
                                             stop = 200, 
                                             by = 10, 
                                             contaminationChanceCutoff = 0.05)
  emptyDropletCutoff = recommend.empty.cutoff(ambProfile)
  ambientProfile = determine.background.to.remove(raw, emptyDropletCutoff, .05)
  seurat[['cleaned']] = CreateAssayObject(remove.background(seurat@assays$RNA@counts, ambientProfile))
  seurat[['percent.mt']] = PercentageFeatureSet(seurat, pattern = "MT-",assay = 'cleaned')
  seurat = subset(seurat, subset=donor_id != "doublet" & percent.mt <= 20)

  return(seurat)
}
```

```{r}
bms753 = ReadSTAR("/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/BMS753/BMS753_Solo.out/",              "/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/BMS753/vireo/", proj = 'BMS753')

cd2314 = ReadSTAR("/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/CD2314/CD2314_Solo.out/",              "/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/CD2314/vireo/", proj = 'CD2314')

deab = ReadSTAR("/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/DEAB/DEAB_Solo.out/",              "/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/DEAB/vireo/", proj = 'DEAB')

e2 = ReadSTAR("/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/E2/E2_Solo.out/",              "/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/E2/vireo/", proj = 'E2')

e2_ra = ReadSTAR("/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/E2-RA/E2-RA_Solo.out/",              "/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/E2-RA/vireo/", proj = 'E2_RA')

e2_tam = ReadSTAR("/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/E2-tam/E2-tam_Solo.out/",              "/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/E2-tam/vireo/", proj = 'E2-tam')

novita = ReadSTAR("/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/novitA/novitA_Solo.out/",              "/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/novitA/vireo/", proj = 'novitA')

ra = ReadSTAR("/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/RA/RA_Solo.out/",              "/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/RA/vireo/", proj = 'RA')

t = ReadSTAR("/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/T/T_Solo.out/",              "/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/T/vireo/", proj = 'T')

t_ra = ReadSTAR("/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/T-RA/T-RA_Solo.out/",              "/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/T-RA/vireo/", proj = 'T_RA')

vita = ReadSTAR("/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/vitA/vitA_Solo.out/",              "/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/vitA/vireo/", proj = 'vitA')


saveRDS(c(bms753,cd2314,deab,e2,e2_ra,e2_tam,novita,ra,t,t_ra,vita),
        file="/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/list.rds")
```

```{r}
orgs = readRDS("/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/list.rds")

orgs[[1]]$donor_id[orgs[[1]]$donor_id == "donor3"] = "A"
orgs[[1]]$donor_id[orgs[[1]]$donor_id == "donor7"] = "B"
orgs[[2]]$donor_id[orgs[[2]]$donor_id == "donor6"] = "A"
orgs[[2]]$donor_id[orgs[[2]]$donor_id == "donor1"] = "B"
orgs[[3]]$donor_id[orgs[[3]]$donor_id == "donor0"] = "A"
orgs[[3]]$donor_id[orgs[[3]]$donor_id == "donor7"] = "B"
orgs[[4]]$donor_id[orgs[[4]]$donor_id == "donor2"] = "A"
orgs[[4]]$donor_id[orgs[[4]]$donor_id == "donor3"] = "B"
orgs[[5]]$donor_id[orgs[[5]]$donor_id == "donor1"] = "A"
orgs[[5]]$donor_id[orgs[[5]]$donor_id == "donor2"] = "B"
orgs[[6]]$donor_id[orgs[[6]]$donor_id == "donor6"] = "A"
orgs[[6]]$donor_id[orgs[[6]]$donor_id == "donor0"] = "B"
orgs[[7]]$donor_id[orgs[[7]]$donor_id == "donor7"] = "A"
#orgs[[7]]$donor_id[orgs[[7]]$donor_id == "donor1"] = "B"
orgs[[8]]$donor_id[orgs[[8]]$donor_id == "donor1"] = "A"
orgs[[8]]$donor_id[orgs[[8]]$donor_id == "donor4"] = "B"
orgs[[9]]$donor_id[orgs[[9]]$donor_id == "donor0"] = "A"
orgs[[9]]$donor_id[orgs[[9]]$donor_id == "donor6"] = "B"
orgs[[10]]$donor_id[orgs[[10]]$donor_id == "donor1"] = "A"
orgs[[10]]$donor_id[orgs[[10]]$donor_id == "donor7"] = "B"
orgs[[11]]$donor_id[orgs[[11]]$donor_id == "donor0"] = "A"
orgs[[11]]$donor_id[orgs[[11]]$donor_id == "donor2"] = "B"

merged = merge(orgs[[1]], orgs[2:11])
Idents(merged) = merged$donor_id
merged = subset(merged, idents=c("A","B"))
gc()
saveRDS(merged, file='/media/chang/HDD-3/chang/20220915_chimericorg_10x/cellranger/kelsey.rds')
```

