---
title: "dev_MG"
output: html_notebook
---

```{r setup, include=FALSE}
library(Seurat)
library(dittoSeq)
library(harmony)
library(SeuratWrappers)
library(scCustomize)
library(scds)
library(presto)
library(viridis)
```

```{r}
# data.dir should be Solo.out dir
ReadSTAR <- function(data.dir, proj = "SeuratObject", feats = 1000, cutoff=1.5,drop.mt=FALSE) {
  data.dir.genefull = paste0(data.dir, "GeneFull_Ex50pAS/raw")
  mtx = file.path(data.dir.genefull, "UniqueAndMult-EM.mtx")
  cells = file.path(data.dir.genefull, "barcodes.tsv")
  features = file.path(data.dir.genefull, "features.tsv")
  if(drop.mt){
    mtx = ReadMtx(mtx = mtx, cells = cells, features = features)
    seurat = as.Seurat(cxds_bcds_hybrid(as.SingleCellExperiment(
      CreateSeuratObject(mtx[!grepl("MT-",rownames(mtx)),], project=proj, min.features=feats)
    )))
  }
  else{
    seurat = as.Seurat(cxds_bcds_hybrid(as.SingleCellExperiment(
    CreateSeuratObject(ReadMtx(mtx = mtx, cells = cells, features = features), 
         project = proj, min.features = feats))))
  }
  data.dir.velo = paste0(data.dir, "/Velocyto/raw")
  cells = file.path(data.dir.velo, "barcodes.tsv")
  features = file.path(data.dir.velo, "features.tsv")
  spliced = file.path(data.dir.velo, "spliced.mtx")
  unspliced = file.path(data.dir.velo, "unspliced.mtx")
  ambi = file.path(data.dir.velo, "ambiguous.mtx")
  spliced = ReadMtx(mtx = spliced, cells = cells, features = features)
  unspliced = ReadMtx(mtx = unspliced, cells = cells, features = features)
  ambi = ReadMtx(mtx = ambi, cells = cells, features = features)
  spliced = spliced + ambi
  spliced = spliced[,colnames(seurat)]
  unspliced = unspliced[,colnames(seurat)]
  seurat[['spliced']] = CreateAssayObject(spliced)
  seurat[['unspliced']] = CreateAssayObject(unspliced)
  seurat[['percent.mt']] = PercentageFeatureSet(seurat, pattern = "MT-",assay = 'RNA')
  seurat = subset(seurat, subset=percent.mt <= 20 & hybrid_score < cutoff)
  return(seurat)
}
```

```{r}
ct = ReadSTAR("/media/chang/HDD-6/chang/mg/rna/MG_Ct/MG_Ct_Solo.out/","GW20_CTX", cutoff = 2)
th = ReadSTAR("/media/chang/HDD-6/chang/mg/rna/MG_Th/MG_Th_Solo.out/","GW20_TH", cutoff = 1)
gw18_multi = ReadSTAR("/media/chang/HDD-6/chang/mg/rna/Galina_Popova/GW18_multiome_RNA_Solo.out/","GW18_Multi", 500,drop.mt= TRUE)
gw22_multi = ReadSTAR("/media/chang/HDD-6/chang/mg/rna/Galina_Popova/GW22_multiome_RNA_Solo.out/","GW22_Multi", 500,drop.mt= TRUE)
gw8 = ReadSTAR("/media/chang/HDD-12/chang/devel/chinese_fetal_mg/HRA000720/HRR208121/GW8_MG_Solo.out/","GW8_CTX")
gw10 = ReadSTAR("/media/chang/HDD-12/chang/devel/chinese_fetal_mg/HRA000720/HRR208122/GW10_MG_Solo.out/","GW10_CTX")
gw12 = ReadSTAR("/media/chang/HDD-12/chang/devel/chinese_fetal_mg/HRA000720/HRR208123/GW12_MG_Solo.out/","GW12_CTX")
gw14 = ReadSTAR("/media/chang/HDD-12/chang/devel/chinese_fetal_mg/HRA000720/HRR208124/GW14_MG_Solo.out/","GW14_CTX")
gw16 = ReadSTAR("/media/chang/HDD-12/chang/devel/chinese_fetal_mg/HRA000720/GW16_MG_Solo.out/","GW16_CTX")
gw23 = ReadSTAR("/media/chang/HDD-12/chang/devel/chinese_fetal_mg/HRA000720/HRR208129/GW23_MG_Solo.out/","GW23_CTX")
gw16_cere = ReadSTAR("/media/chang/HDD-12/chang/devel/chinese_fetal_mg/HRA002150/Cerebellum-GW16_0_1_H5TNLDSXY/", "GW16_cerebellum")

```

```{r}
rm(ReadSTAR)
obj = mget(ls())
merged = merge(obj[[1]], obj[2:length(obj)])
merged[["percent.mt"]] = PercentageFeatureSet(merged, pattern = "^MT-")
merged = subset(merged, subset=hybrid_score < 1 & percent.mt < 20)
```

```{r}
merged = SCTransform(merged, vst.flavor='v2', ncells=NULL, n_genes=NULL)
merged = RunPCA(merged)
merged = RunUMAP(merged, dims=1:30)
```
```{r}
merged$Batch[merged$Batch == "GW20_TH"] = "GW20"
merged$Batch[merged$Batch == "GW20_CTX"] = "GW20"
merged = RunHarmony(merged, group.by.vars = 'Batch', assay.use = "SCT", plot_convergence = T)
merged = RunUMAP(merged, dims=1:50, reduction='harmony')
#DimPlot(merged, group.by='orig.ident', cols=dittoColors(), label=T) + NoAxes()
```

