---
title: "iTF_MG"
output: html_notebook
---


```{r setup, include=FALSE}
library(Seurat)
library(dittoSeq)
library(harmony)
library(SeuratWrappers)
library(scCustomize)
library(scds)
library(DropletUtils)
```

```{r}
# data.dir should be Solo.out dir
ReadSTAR <- function(data.dir, proj = "SeuratObject", feats = 1000) {
  # test dir /media/chang/HDD-1/chang/fastqs/ctrl/ctrl085_L_Solo.out/
  data.dir.genefull = paste0(data.dir, "/GeneFull_Ex50pAS/raw")
  mtx = file.path(data.dir.genefull, "UniqueAndMult-EM.mtx")
  cells = file.path(data.dir.genefull, "barcodes.tsv")
  features = file.path(data.dir.genefull, "features.tsv")
  seurat = as.Seurat(cxds_bcds_hybrid(as.SingleCellExperiment
                                      (CreateSeuratObject(ReadMtx
                                      (mtx = mtx, cells = cells, 
                                      features = features), 
                                      project = proj, min.features = feats))))
  data.dir.velo = paste0(data.dir, "/Velocyto/raw")
  cells = file.path(data.dir.velo, "barcodes.tsv")
  features = file.path(data.dir.velo, "features.tsv")
  spliced = file.path(data.dir.velo, "spliced.mtx")
  unspliced = file.path(data.dir.velo, "unspliced.mtx")
  ambi = file.path(data.dir.velo, "ambiguous.mtx")
  spliced = ReadMtx(mtx = spliced, cells = cells, features = features)
  unspliced = ReadMtx(mtx = unspliced, cells = cells, features = features)
  ambi = ReadMtx(mtx = ambi, cells = cells, features = features)
  spliced = spliced + ambi
  spliced = spliced[,colnames(seurat)]
  unspliced = unspliced[,colnames(seurat)]
  seurat[['spliced']] = CreateAssayObject(spliced)
  seurat[['unspliced']] = CreateAssayObject(unspliced)
  return(seurat)
}

ReadSTAR_Raw <- function(data.dir) {
  # test dir /media/chang/HDD-1/chang/fastqs/ctrl/ctrl085_L_Solo.out/
  data.dir.genefull = paste0(data.dir, "/GeneFull_Ex50pAS/raw")
  mtx = file.path(data.dir.genefull, "UniqueAndMult-EM.mtx")
  cells = file.path(data.dir.genefull, "barcodes.tsv")
  features = file.path(data.dir.genefull, "features.tsv")
  mtx = ReadMtx(mtx = mtx, cells = cells, features = features)
  return(mtx)
}
```

```{r}
guides=read.csv("/media/chang/HDD-1/chang/itf/cite_seq_input.txt", header=0)
guides = c(guides$V2,"unmapped")

lane1 = ReadMtx(mtx = '/media/chang/HDD-1/chang/itf/lane1_crispr/count/umi_count/matrix.mtx.gz',cells = '/media/chang/HDD-1/chang/itf/lane1_crispr/count/umi_count/barcodes.tsv.gz',features = '/media/chang/HDD-1/chang/itf/lane1_crispr/count/umi_count/features.tsv.gz',feature.column = 1);
rownames(lane1) = guides
lane1 = lane1[c(1:81),]
write10xCounts("/media/chang/HDD-1/chang/itf/lane1_scar/lane1.h5",x=lane1,version='3',type = "HDF5")

lane2 = ReadMtx(mtx = '/media/chang/HDD-1/chang/itf/lane2_crispr/count/umi_count/matrix.mtx.gz',cells = '/media/chang/HDD-1/chang/itf/lane2_crispr/count/umi_count/barcodes.tsv.gz',features = '/media/chang/HDD-1/chang/itf/lane2_crispr/count/umi_count/features.tsv.gz',feature.column = 1);
rownames(lane2) = guides
lane2 = lane2[c(1:81),]
write10xCounts("/media/chang/HDD-1/chang/itf/lane2_scar/lane2.h5",x=lane2,version='3',type = "HDF5")

lane3 = ReadMtx(mtx = '/media/chang/HDD-1/chang/itf/lane3_crispr/count/umi_count/matrix.mtx.gz',cells = '/media/chang/HDD-1/chang/itf/lane3_crispr/count/umi_count/barcodes.tsv.gz',features = '/media/chang/HDD-1/chang/itf/lane3_crispr/count/umi_count/features.tsv.gz',feature.column = 1);
rownames(lane3) = guides
lane3 = lane3[c(1:81),]
write10xCounts("/media/chang/HDD-1/chang/itf/lane3_scar/lane3.h5",x=lane3,version='3',type = "HDF5")

lane4 = ReadMtx(mtx = '/media/chang/HDD-1/chang/itf/lane4_crispr/count/umi_count/matrix.mtx.gz',cells = '/media/chang/HDD-1/chang/itf/lane4_crispr/count/umi_count/barcodes.tsv.gz',features = '/media/chang/HDD-1/chang/itf/lane4_crispr/count/umi_count/features.tsv.gz',feature.column = 1);
rownames(lane4) = guides
lane4 = lane4[c(1:81),]
write10xCounts("/media/chang/HDD-1/chang/itf/lane4_scar/lane4.h5",x=lane4,version='3',type = "HDF5")

lane1 = ReadSTAR_Raw("/media/chang/HDD-1/chang/itf/lane1_Solo.out/")
lane2 = ReadSTAR_Raw("/media/chang/HDD-1/chang/itf/lane2_Solo.out/")
lane3 = ReadSTAR_Raw("/media/chang/HDD-1/chang/itf/lane3_Solo.out/")
lane4 = ReadSTAR_Raw("/media/chang/HDD-1/chang/itf/lane4_Solo.out/")
write10xCounts("/media/chang/HDD-1/chang/itf/lane1_scar/lane1_rna.h5",x=lane1,version='3',type = "HDF5")
write10xCounts("/media/chang/HDD-1/chang/itf/lane2_scar/lane2_rna.h5",x=lane2,version='3',type = "HDF5")
write10xCounts("/media/chang/HDD-1/chang/itf/lane3_scar/lane3_rna.h5",x=lane3,version='3',type = "HDF5")
write10xCounts("/media/chang/HDD-1/chang/itf/lane4_scar/lane4_rna.h5",x=lane4,version='3',type = "HDF5")
```

```{r}
```
