---
title: "process_all_samples"
output: html_document
---
```{r setup, include=FALSE}
library(Seurat)
library(dittoSeq)
library(harmony)
library(SeuratWrappers)
library(scCustomize)
library(scds)
library(presto)
library(viridis)
library(stringr)
library(transformGamPoi)
library(FastCAR)
library(Matrix)
library(DropletQC)
library(SingleCellExperiment)
path = '/media/chang/HDD-8/chang/aparna/'
```

```{r}
# data.dir should be Solo.out dir
ReadSTAR <- function(data.dir, proj = "SeuratObject", feats = 500, ratio=.1,
                     counts = 1000, sample="Sample", doublet=TRUE) {
  data.dir.genefull = paste0(data.dir, "GeneFull_Ex50pAS/raw")
  mtx = file.path(data.dir.genefull, "UniqueAndMult-EM.mtx")
  cells = file.path(data.dir.genefull, "barcodes.tsv")
  features = file.path(data.dir.genefull, "features.tsv")
  raw = ReadMtx(mtx = mtx, cells = cells, features = features)
  
  seurat = CreateSeuratObject(raw, project=proj, min.features = feats)
  
  data.dir.velo = paste0(data.dir, "/Velocyto/raw")
  cells = file.path(data.dir.velo, "barcodes.tsv")
  features = file.path(data.dir.velo, "features.tsv")
  spliced = file.path(data.dir.velo, "spliced.mtx")
  unspliced = file.path(data.dir.velo, "unspliced.mtx")
  ambi = file.path(data.dir.velo, "ambiguous.mtx")
  spliced = ReadMtx(mtx = spliced, cells = cells, features = features)
  unspliced = ReadMtx(mtx = unspliced, cells = cells, features = features)
  ambi = ReadMtx(mtx = ambi, cells = cells, features = features)
  spliced = spliced + ambi

  seurat[['unspliced']] = CreateAssayObject(unspliced[,colnames(seurat)])
  seurat[['spliced']] = CreateAssayObject(spliced[,colnames(seurat)])
  seurat$droplet_qc_ratio = seurat$nCount_unspliced / seurat$nCount_RNA

  md = seurat@meta.data[,c("droplet_qc_ratio","nCount_RNA" )]
  md$nCount_RNA = as.integer(md$nCount_RNA)
  
  calls = identify_empty_drops(md, nf_rescue = ratio, umi_rescue=counts)
  seurat$cell_status = calls$cell_status

  seurat = subset(seurat, subset=cell_status == "cell")
  te = Read10X(paste0(data.dir,"/IRescue_out"))
  te = te[,colnames(seurat)]
  seurat[['TE']] = CreateAssayObject(te)

  ambProfile = describe.ambient.RNA.sequence(fullMatrix = raw, 
                                             start = 10, 
                                             stop = 200, 
                                             by = 10, 
                                             contaminationChanceCutoff = 0.05)
  emptyDropletCutoff = recommend.empty.cutoff(ambProfile)
  ambientProfile = determine.background.to.remove(raw, emptyDropletCutoff, .05)
  seurat[['cleaned']] = CreateAssayObject(remove.background(seurat@assays$RNA@counts, ambientProfile))
  
  sce = cxds_bcds_hybrid(SingleCellExperiment(list(counts=seurat@assays$cleaned@counts)))
  seurat$hybrid_score = sce$hybrid_score

  seurat[['percent.mt']] = PercentageFeatureSet(seurat, pattern = "MT-",assay = 'cleaned')
  
  if(doublet == TRUE){
    n_cells = dim(seurat)[2]
    if (n_cells >= 15000){
      seurat = subset(seurat, subset=percent.mt <= 20 & hybrid_score < 1)
    } else if(n_cells >= 10000){
      seurat = subset(seurat, subset=percent.mt <= 20 & hybrid_score < 1.25)
    } else if(n_cells >= 5000){
      seurat = subset(seurat, subset=percent.mt <= 20 & hybrid_score < 1.5)
    } else if(n_cells < 5000){
      seurat = subset(seurat, subset=percent.mt <= 20 & hybrid_score < 1.75)
    }
  } else{
    seurat = subset(seurat, subset=percent.mt <= 20)
  }
  seurat$Sample = sample
  return(seurat)
}
```

```{r}
dirs = '/media/chang/HDD-8/chang/aparna/April2020NeMoSubmission/Solo.out/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW16_v3")
})
seurat = merge(seurat[[1]], seurat[2:length(samples)])

seurat = subset(seurat, subset=orig.ident == "Temporal", invert=T)
seurat$Area = tolower(seurat$orig.ident)
seurat$Age = "GW16"
seurat$Area[seurat$Area == "ss"] = "somato"
```

```{r}
dirs = '/media/chang/HDD-8/chang/aparna/cs19/Solo.out/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat2 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "CS19")
})
seurat2 = merge(seurat2[[1]], seurat2[2:length(samples)])
seurat2 = subset(seurat2, subset=orig.ident=="CS19thalamus")
seurat2$orig.ident = "CS19_thalamus"
```

```{r}
dirs = '/media/chang/HDD-8/chang/aparna/biopsych2022/Solo.out/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat3 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "FC",ratio = .2,
           feats = 1000, counts = 2000)
})
seurat3 = merge(seurat3[[1]], seurat3[2:length(samples)])
seurat3$Sample = "510"
seurat3$Sample[grepl("611", seurat3$orig.ident)] = "611"
seurat3$Sample[grepl("993", seurat3$orig.ident)] = "993"
seurat3$Area = "pfc"
seurat3$Area[grepl("Thal", seurat3$Area)] = "thalamus"
seurat3$Age = "GW16"
```

```{r}
dirs = '/media/chang/HDD-8/chang/aparna/first/Solo.out/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat4 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "First")
})
seurat4 = merge(seurat4[[1]], seurat4[2:length(samples)])
seurat4 = subset(seurat4, subset=orig.ident=="CS15_2_thalamus")
seurat4$Sample = "CS15"
seurat4$Age = "GW6"
```

```{r}
dirs = '/media/chang/HDD-8/chang/aparna/GW14/Solo.out/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat5 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW14")
})
seurat5 = merge(seurat5[[1]], seurat5[2:length(samples)])
seurat5$Area = "motor"
seurat5$Area[seurat5$orig.ident == "GW14occipital"] = "occipital"
seurat5$Area[seurat5$orig.ident == "GW14thalamus"] = "thalamus"
```

```{r}
dirs = '/media/chang/HDD-8/chang/aparna/gw/Solo.out/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat6 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW22")
})
seurat6 = merge(seurat6[[1]], seurat6[2:length(samples)])

seurat6$Sample[grepl("GW22T", seurat6$orig.ident)] = "GW22T"
seurat6$Area = "pfc"
seurat6$Area[grepl("motor", seurat6$orig.ident)] = "motor"
seurat6$Area[grepl("parietal", seurat6$orig.ident)] = "parietal"
seurat6$Area[grepl("somato", seurat6$orig.ident)] = "somato"
seurat6$Area[grepl("v1", seurat6$orig.ident)] = "v1"
seurat6$Area[grepl("thalamus", seurat6$orig.ident)] = "somato"
seurat6$Age = "GW22"
```

```{r}
dirs = '/media/chang/HDD-8/chang/aparna/GW18/Solo.out/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat7 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW18")
})
seurat7 = merge(seurat7[[1]], seurat7[2:length(samples)])

seurat7$Age = "GW18"
seurat7$Area = "pfc"
seurat7$Area[grepl("motor", seurat7$orig.ident)] = "motor"
seurat7$Area[grepl("parietal", seurat7$orig.ident)] = "parietal"
seurat7$Area[grepl("temporal", seurat7$orig.ident)] = "temporal"
seurat7$Area[grepl("somato", seurat7$orig.ident)] = "somato"
seurat7$Area[grepl("V1", seurat7$orig.ident)] = "v1"
seurat7$Area[grepl("thalamus", seurat7$orig.ident)] = "thalamus"
```

```{r}
dirs = '/media/chang/HDD-8/chang/aparna/GW25/Solo.out/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat8 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW25")
})
seurat8 = merge(seurat8[[1]], seurat8[2:length(samples)])

seurat8$Age = "GW25"
seurat8$Area = "cingulate"
seurat8$Area[grepl("PFC", seurat8$orig.ident)] = "pfc"
seurat8$Area[grepl("motor", seurat8$orig.ident)] = "motor"
seurat8$Area[grepl("Par", seurat8$orig.ident)] = "parietal"
seurat8$Area[grepl("temporal", seurat8$orig.ident)] = "temporal"
seurat8$Area[grepl("insula", seurat8$orig.ident)] = "insula"
seurat8$Area[grepl("pulminarthal", seurat8$orig.ident)] = "pulminarthal"
seurat8$Area[grepl("thalamus", seurat8$orig.ident)] = "thalamus"
```

```{r}
dirs = '/media/chang/HDD-8/chang/aparna/Jan2020_NeMoSubmission/Solo.out/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat9 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW18_2")
})
seurat9 = merge(seurat9[[1]], seurat9[2:length(samples)])

seurat9$Age = "GW18"
seurat9$Area = "claustrum"
seurat9$Area[grepl("PFC", seurat9$orig.ident)] = "pfc"
seurat9$Area[grepl("motor", seurat9$orig.ident)] = "motor"
seurat9$Area[grepl("parietal", seurat9$orig.ident)] = "parietal"
seurat9$Area[grepl("Par", seurat9$orig.ident)] = "parietal"
seurat9$Area[grepl("temporal", seurat9$orig.ident)] = "temporal"
seurat9$Area[grepl("somato", seurat9$orig.ident)] = "somato"
seurat9$Area[grepl("Temp", seurat9$orig.ident)] = "temporal"
seurat9$Area[grepl("V1", seurat9$orig.ident)] = "v1"
seurat9$Area[grepl("dorsal_thalamus", seurat9$orig.ident)] = "dorsal_thalamus"
seurat9$Area[grepl("ventral_thalamus", seurat9$orig.ident)] = "ventral_thalamus"
seurat9 = subset(seurat9, subset=orig.ident=='GW18_2_claustrum', invert=T)
```

```{r}
dirs = '/media/chang/HDD-8/chang/aparna/January2019NeMoSubmission/Solo.out/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat10 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW20_34")
})
seurat10 = merge(seurat10[[1]], seurat10[2:length(samples)])

seurat10$Age = "GW20"
seurat10$Area = "caudate"
seurat10$Area[grepl("dorsalthalamus", seurat10$orig.ident)] = "dorsal_thalamus"
seurat10$Area[grepl("ventralthalamus", seurat10$orig.ident)] = "ventral_thalamus"
seurat10$Area[grepl("parietal", seurat10$orig.ident)] = "parietal"
seurat10$Area[grepl("motor", seurat10$orig.ident)] = "motor"
seurat10$Area[grepl("PFC", seurat10$orig.ident)] = "pfc"
seurat10$Area[grepl("V1", seurat10$orig.ident)] = "v1"

seurat10 = subset(seurat10, subset=orig.ident=='caudate_34', invert=T)

```

```{r}
dirs = '/media/chang/HDD-8/chang/aparna/JulyNeMoSubmission/Solo.out/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat11 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW20")
})
seurat11 = merge(seurat11[[1]], seurat11[2:length(samples)])

seurat11$new = seurat11$orig.ident
seurat11$new[seurat11$orig.ident == "GW20V1"] = "GW20parietal"
seurat11$new[seurat11$orig.ident == "GW20somato"] = "GW20PFC"
seurat11$new[seurat11$orig.ident == "GW20cingulate_corpus"] = "GW20hypoventalmedial"
seurat11$new[seurat11$orig.ident == "GW20claustrum"] = "GW20MGE"
seurat11$new[seurat11$orig.ident == "GW20preoptic"] = "GW20caudalthalamus"
seurat11$new[seurat11$orig.ident == "GW20motor"] = "GW20CGE"
seurat11$new[seurat11$orig.ident == "GW20LGE"] = "GW20dorsalthalamus"
seurat11$new[seurat11$orig.ident == "GW20putanum"] = "GW20ventralthalamus"

seurat11$new[seurat11$orig.ident == "GW20parietal"] = "GW20V1"
seurat11$new[seurat11$orig.ident == "GW20PFC"] = "GW20somato"
seurat11$new[seurat11$orig.ident == "GW20hypoventalmedial"] = "GW20cingulatecorpus"
seurat11$new[seurat11$orig.ident == "GW20MGE"] = "GW20claustrum"
seurat11$new[seurat11$orig.ident == "GW20caudalthalamus"] = "GW20preoptic"
seurat11$new[seurat11$orig.ident == "GW20CGE"] = "GW20motor"
seurat11$new[seurat11$orig.ident == "GW20dorsalthalamus"] = "GW20LGE"
seurat11$new[seurat11$orig.ident == "GW20_ventral_thalamus"] = "GW20putanum"
seurat11$orig.ident = seurat11$new

seurat11$Age = "GW20"
seurat11 = subset(seurat11, subset=orig.ident %in% c("GW20_ventral_thalamus",
                                                     "GW20caudalthalamus",
                                                     "GW20cingulate_corpus",
                                                     "GW20dorsalthalamus",
                                                     "GW20motor",
                                                     "GW20parietal",
                                                     "GW20PFC",
                                                     "GW20somato",
                                                     "GW20V1"))

seurat11$Area = "ventral_thalamus"
seurat11$Area[seurat11$orig.ident == "GW20caudalthalamus"] = "caudal_thalamus"
seurat11$Area[seurat11$orig.ident == "GW20cingulate_corpus"] = "cingulate"
seurat11$Area[seurat11$orig.ident == "GW20dorsalthalamus"] = "dorsal_thalamus"
seurat11$Area[seurat11$orig.ident == "GW20motor"] = "motor"
seurat11$Area[seurat11$orig.ident == "GW20parietal"] = "parietal"
seurat11$Area[seurat11$orig.ident == "GW20PFC"] = "pfc"
seurat11$Area[seurat11$orig.ident == "GW20V1"] = "v1"
```

```{r}
dirs = '/media/chang/HDD-8/chang/aparna/OctoberNeMoSubmission/Solo.out/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat12 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "CS22")
})
seurat12 = merge(seurat12[[1]], seurat12[2:length(samples)])
seurat12 = subset(seurat12, subset=orig.ident=="CS22_thalamus")
```

```{r}
dirs = '/media/chang/HDD-8/chang/aparna/kriegsteina-10x-v2-pool/Solo.out/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat13 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "CS22_2")
})
seurat13 = merge(seurat13[[1]], seurat13[2:length(samples)])
seurat13 = subset(seurat13, subset=orig.ident=="CS22_Thalamus")
seurat13$orig.ident = "CS22_2_thalamus"
```

```{r}
first = merge(seurat4, c(seurat2, seurat12, seurat13))
first$Age = "GW10"
first$Age[first$Sample == "CS19"] = "GW8.5"
first$Age[first$Sample == "CS15"] = "GW6"
first = subset(first, subset=nFeature_cleaned >= 500)

first = SCTransform(first, vst.flavor="v2", n_genes=NULL, 
                    ncells=NULL, assay = 'cleaned')
first = RunPCA(first, npcs = 30)
first = RunHarmony(first, group.by.vars = "Sample", 
                   plot_convergence = T, assay.use = "SCT")
first = RunUMAP(first, dims=1:30, reduction='harmony')
first = FindNeighbors(first, dims=1:30, reduction = 'harmony')
first = FindClusters(first, resolution = .6)

first = SCTransform(first, vst.flavor="v2", n_genes=NULL, 
                    ncells=NULL, assay = 'TE',new.assay.name = "SCT_TE")

DimPlot_scCustom(first, group.by="Sample") + NoAxes()
DimPlot_scCustom(first,label=T) + NoAxes()

test = FindAllMarkers(first, assay = "SCT_TE", only.pos = T)
top5_markers <- Extract_Top_Markers(marker_dataframe = test, num_genes = 5, 
                                    named_vector = FALSE, make_unique = TRUE)
te = c("DNA/TcMar-Tigger.36","LTR/ERV1.142","LTR/ERVL-MaLR.50","SINE/Alu.24","LINE/L1.3","DNA/hAT-Ac")
FeaturePlot(first, features = te, order=T, max.cutoff = 'q99', ncol = 3) & NoAxes() & scale_color_viridis()

FeaturePlot(first, features = c("EOMES"), order=T, max.cutoff = 'q99') & NoAxes() & scale_color_viridis()
```

```{r}
merged = merge(seurat, c(seurat2,seurat3,seurat4,seurat5,seurat6,seurat7,seurat8,
                         seurat9,seurat10,seurat11,seurat12,seurat13))

rm(seurat);rm(seurat2);rm(seurat3);rm(seurat4);rm(seurat5);rm(seurat6);rm(seurat7);rm(seurat8);rm(seurat9);rm(seurat10);rm(seurat11);rm(seurat12);rm(seurat13);

merged = subset(merged, subset=nFeature_cleaned >= 500)

merged$Age[merged$orig.ident == "CS12Diencephalon"] = "GW5"
merged$Age[merged$orig.ident == "CS14_3_diencephalon"] = "GW5.5"
merged$Age[merged$orig.ident == "CS15_2_thalamus"] = "GW6"
merged$Age[merged$orig.ident == "CS19_thalamus"] = "GW8.5"
merged$Age[merged$orig.ident == "CS22_2_thalamus"] = "GW10"
merged$Age[merged$orig.ident == "CS22_thalamus"] = "GW10"
merged$Age[grepl("GW14", merged$orig.ident)] = "GW14"
merged$Area[grepl("CS", merged$orig.ident)] = "thalamus"

thal$Sample[thal$orig.ident == 'CS12Diencephalon'] = "CS12"
thal$Sample[thal$orig.ident == 'CS14_3_diencephalon'] = "CS14"

saveRDS(merged,file="/media/chang/HDD-8/chang/aparna/thal.rds")
```