---
title: "process_all_samples"
output: html_document
---
```{r setup, include=FALSE}
library(Seurat)
library(dittoSeq)
library(harmony)
library(SeuratWrappers)
library(scCustomize)
library(scds)
library(presto)
library(viridis)
library(stringr)
library(transformGamPoi)
library(FastCAR)
library(Matrix)

path = '/media/chang/HDD-12/chang/devel'
```

```{r}
ReadSTARaw <- function(data.dir, proj = "SeuratObject", feats = 500, 
                     counts = 1000, sample="Sample", doublet=TRUE) {
  data.dir.genefull = paste0(data.dir, "GeneFull_Ex50pAS/raw")
  mtx = file.path(data.dir.genefull, "UniqueAndMult-EM.mtx")
  cells = file.path(data.dir.genefull, "barcodes.tsv")
  features = file.path(data.dir.genefull, "features.tsv")
  raw = ReadMtx(mtx = mtx, cells = cells, features = features)
}
merged_seurat$log10GenesPerUMI <- log10(merged_seurat$nFeature_RNA) / log10(merged_seurat$nCount_RNA)
# data.dir should be Solo.out dir
ReadSTAR <- function(data.dir, proj = "SeuratObject", feats = 500, 
                     counts = 1000, sample="Sample", doublet=TRUE) {
  data.dir.genefull = paste0(data.dir, "GeneFull_Ex50pAS/raw")
  mtx = file.path(data.dir.genefull, "UniqueAndMult-EM.mtx")
  cells = file.path(data.dir.genefull, "barcodes.tsv")
  features = file.path(data.dir.genefull, "features.tsv")
  raw = ReadMtx(mtx = mtx, cells = cells, features = features)
  seurat = subset(CreateSeuratObject(raw, project = proj, min.features = feats),
                  subset=nCount_RNA >= counts)
  
  ambProfile = describe.ambient.RNA.sequence(fullMatrix = raw, 
                                             start = 10, 
                                             stop = 200, 
                                             by = 10, 
                                             contaminationChanceCutoff = 0.05)
  emptyDropletCutoff = recommend.empty.cutoff(ambProfile)
  ambientProfile = determine.background.to.remove(raw, emptyDropletCutoff, .05)
  seurat = subset(CreateSeuratObject(remove.background(seurat@assays$RNA@counts, ambientProfile),
                                     project = proj, min.features = feats), subset=nCount_RNA >= 800)
  
  seurat = as.Seurat(cxds_bcds_hybrid(as.SingleCellExperiment(seurat)))
  seurat$ident = NULL
  
  data.dir.velo = paste0(data.dir, "/Velocyto/raw")
  cells = file.path(data.dir.velo, "barcodes.tsv")
  features = file.path(data.dir.velo, "features.tsv")
  spliced = file.path(data.dir.velo, "spliced.mtx")
  unspliced = file.path(data.dir.velo, "unspliced.mtx")
  ambi = file.path(data.dir.velo, "ambiguous.mtx")
  spliced = ReadMtx(mtx = spliced, cells = cells, features = features)
  unspliced = ReadMtx(mtx = unspliced, cells = cells, features = features)
  ambi = ReadMtx(mtx = ambi, cells = cells, features = features)
  spliced = spliced + ambi
  
  ambProfile = describe.ambient.RNA.sequence(fullMatrix = spliced, 
                                             start = 10, 
                                             stop = 200, 
                                             by = 10, 
                                             contaminationChanceCutoff = 0.05)
  emptyDropletCutoff = recommend.empty.cutoff(ambProfile)
  ambientProfile = determine.background.to.remove(spliced, emptyDropletCutoff, .05)
  seurat[['spliced']] = CreateAssayObject(remove.background(spliced[,colnames(seurat)], 
                                                            ambientProfile))
  
  ambProfile = describe.ambient.RNA.sequence(fullMatrix = unspliced, 
                                             start = 10, 
                                             stop = 200, 
                                             by = 10, 
                                             contaminationChanceCutoff = 0.05)
  emptyDropletCutoff = recommend.empty.cutoff(ambProfile)
  ambientProfile = determine.background.to.remove(unspliced, emptyDropletCutoff, .05)
  seurat[['unspliced']] = CreateAssayObject(remove.background(unspliced[,colnames(seurat)], 
                                                            ambientProfile))  
  
  seurat[['percent.mt']] = PercentageFeatureSet(seurat, pattern = "MT-",assay = 'RNA')
  if(doublet == TRUE){
    n_cells = dim(seurat)[2]
    if (n_cells >= 15000){
      seurat = subset(seurat, subset=percent.mt <= 20 & hybrid_score < 1)
    } else if(n_cells >= 10000){
      seurat = subset(seurat, subset=percent.mt <= 20 & hybrid_score < 1.25)
    } else if(n_cells >= 5000){
      seurat = subset(seurat, subset=percent.mt <= 20 & hybrid_score < 1.5)
    } else if(n_cells < 5000){
      seurat = subset(seurat, subset=percent.mt <= 20 & hybrid_score < 1.75)
    }
  } else{
    seurat = subset(seurat, subset=percent.mt <= 20)
  }
  seurat$Sample = sample
  #seurat$orig.ident = paste0(sample, "_", seurat$orig.ident)
  return(seurat)
}
```

```{r}
# science interneuron paper
dirs = '/media/chang/HDD-12/chang/devel/science_inter/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "Shi_2021")
})
seurat = merge(seurat[[1]], seurat[2:length(samples)])
seurat$Sample = seurat$orig.ident
seurat$Sample[grepl("GE_GW12_2", seurat$orig.ident)] = "GE_GW12_2"
seurat$Area = "GE"
seurat$Area[grepl("MGE", seurat$orig.ident)] = "MGE"
seurat$Area[grepl("LGE", seurat$orig.ident)] = "LGE"
seurat$Area[grepl("CGE", seurat$orig.ident)] = "CGE"
seurat$Age = "GW18"
seurat$Age[grepl("GW12", seurat$orig.ident)] =  "GW12"
seurat$Age[grepl("GW13", seurat$orig.ident)] =  "GW13"
seurat$Age[grepl("GW16", seurat$orig.ident)] =  "GW16"
seurat$Age[grepl("GW18", seurat$orig.ident)] =  "GW18"
seurat$Age[grepl("GW9", seurat$orig.ident)] =  "GW9"

```

```{r}
dirs = '/media/chang/HDD-12/chang/devel/nature_neuro_inter/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat2 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "Yu_2021")
})
seurat2 = merge(seurat2[[1]], seurat2[2:length(samples)])
seurat2$Sample = seurat2$orig.ident
seurat2$Area = "GE"
seurat2$Age = "GW11"
seurat2$Age[grepl("GW12", seurat2$orig.ident)] =  "GW12"
seurat2$Age[grepl("GW10", seurat2$orig.ident)] =  "GW10"
seurat2$Age[grepl("GW9", seurat2$orig.ident)] =  "GW9"
```

```{r}
dirs = '/media/chang/HDD-12/chang/devel/china_hippocampus/STARSolo/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat3 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "Zhong_2020")
})
seurat3 = merge(seurat3[[1]], seurat3[2:length(samples)])
seurat3$orig.ident = paste0(seurat3$orig.ident, "_Hippo")
seurat3$Sample = seurat3$orig.ident
seurat3$Area = "Hippocampus"
seurat3$Age = "GW20"
seurat3$Age[grepl("GW22", seurat3$orig.ident)] =  "GW22"
seurat3$Age[grepl("GW16", seurat3$orig.ident)] =  "GW16"
seurat3$Age[grepl("GW18", seurat3$orig.ident)] =  "GW18"
seurat3$Age[grepl("GW25", seurat3$orig.ident)] =  "GW25"
seurat3$Age[grepl("GW27", seurat3$orig.ident)] =  "GW27"
```

```{r}
dirs = '/media/chang/HDD-12/chang/devel/china_hypo/STARSolo/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat4 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "Zhou_2021")
})
seurat4 = merge(seurat4[[1]], seurat4[2:length(samples)])
seurat4$orig.ident = paste0(seurat4$orig.ident, "_Hypo")
seurat4$Sample = seurat4$orig.ident
seurat4$Sample[grepl("GW18_02", seurat4$orig.ident)] = "GW18_02_Hypo"
seurat4$Sample[grepl("GW8", seurat4$orig.ident)] = "GW8_Hypo"
seurat4$Sample[grepl("GW5", seurat4$orig.ident)] = "GW5_Hypo"
seurat4$Area = "Hypothalamus"
seurat4$Age = "GW18"
seurat4$Age[grepl("GW20", seurat4$orig.ident)] =  "GW20"
seurat4$Age[grepl("GW15", seurat4$orig.ident)] =  "GW15"
seurat4$Age[grepl("GW12", seurat4$orig.ident)] =  "GW12"
seurat4$Age[grepl("GW10", seurat4$orig.ident)] =  "GW10"
seurat4$Age[grepl("GW8", seurat4$orig.ident)] =  "GW8"
```

```{r}
dirs = '/media/chang/HDD-12/chang/devel/gbm_fetal/STARSolo_fetal_ol/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat5 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "Fetal_OL")
})
seurat5 = merge(seurat5[[1]], seurat5[2:length(samples)])
seurat5$Sample = paste0(seurat5$orig.ident, "_OL")
seurat5$Area ="OL"
seurat5$Age = "Second"
```

```{r}
dirs = '/media/chang/HDD-12/chang/devel/gbm_fetal/STARSolo_gbm_fetal/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat6 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GBM_Fetal")
})
seurat6 = merge(seurat6[[1]], seurat6[2:length(samples)])
seurat6$Sample = substr(seurat6$orig.ident,start = 1, stop = 6)
seurat6$Sample = paste0(seurat6$Sample,"_2")
seurat6$Sample[grepl("NSC1", seurat6$orig.ident)] = "NSC1"
seurat6$Area = substr(seurat6$orig.ident,start = 8, stop = 12)
seurat6$Area[grepl("CD133", seurat6$orig.ident)] = "CD133"
seurat6$Age = "GW21"
seurat6$Age[grepl("HFA567", seurat6$orig.ident)] = "GW13"
seurat6$Age[grepl("HFA571", seurat6$orig.ident)] = "GW17"
seurat6$Age[grepl("HFA570", seurat6$orig.ident)] = "GW19"
```

```{r}
dirs = '/media/chang/HDD-12/chang/devel/german_cerebellum/STARSolo/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat7 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "German_Cerebellum")
})
seurat7 = merge(seurat7[[1]], seurat7[2:length(samples)])
seurat7$Area = "Cerebellum"

meta = read.table("/media/chang/HDD-12/chang/devel/german_cerebellum/meta.txt", 
                  sep='\t', row.names = 1)
meta = meta[unique(seurat7$orig.ident),]
seurat7$Sample = plyr::mapvalues(seurat7$orig.ident, rownames(meta), meta$V4)
seurat7$Age = plyr::mapvalues(seurat7$orig.ident, rownames(meta), meta$V6)
seurat7$Age[grepl("11",seurat7$Age)] = "GW13"
seurat7$Age[grepl("17",seurat7$Age)] = "GW19"
seurat7$Age[grepl("20",seurat7$Age)] = "GW22"
seurat7$Age[grepl("^9",seurat7$Age)] = "GW11"
seurat7$Age[grepl("CS18",seurat7$Age)] = "GW8"
seurat7$Age[grepl("CS19",seurat7$Age)] = "GW8.5"
seurat7$Age[grepl("CS22",seurat7$Age)] = "GW10"

seurat7$Sex = plyr::mapvalues(seurat7$orig.ident, rownames(meta), meta$V5)
```

```{r}
dirs = '/media/chang/HDD-12/chang/devel/MSAP08/STARSolo/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat8 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "Alex")
})
seurat8 = merge(seurat8[[1]], seurat8[2:length(samples)])
seurat8$Sample = "GW23_Alex"
seurat8$Age = "GW23"
seurat8$Area = "Midbrain"
seurat8$Area[grepl("Rhombencephalon", seurat8$orig.ident)] = "Hindbrain"
```

```{r}
dirs = '/media/chang/HDD-12/chang/devel/brainstem/STARSolo/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat9 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "Brainstem")
})
seurat9 = merge(seurat9[[1]], seurat9[2:length(samples)])
seurat9$Sample = "GW17_BS"
seurat9$Sample[grepl("GW19", seurat9$orig.ident)] = "GW19_BS"
seurat9$Area = "Brainstem"
```

```{r}
dirs = '/media/chang/HDD-12/chang/devel/ziffra/STARSolo/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat10 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "Ziffra")
})
seurat10 = merge(seurat10[[1]], seurat10[2:length(samples)])
seurat10$Sample = seurat10$orig.ident
seurat10$Area = "Cortex"
seurat10$Age = "GW17"
seurat10$Age[seurat10$orig.ident == "Cortex_GW21_Fresh"] = "GW21"
```

```{r}
dirs = '/media/chang/HDD-12/chang/devel/chinese_fetal_mg/HRA000720/STARSolo/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
seurat11 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "Cortex_MG")
})
seurat11 = merge(seurat11[[1]], seurat11[2:length(samples)])
seurat11$Area = "Cortex"
seurat11$Sample = seurat11$orig.ident
seurat11$Sample[grepl("GW16_MG_", seurat11$orig.ident)] = 'GW16_MG_2'
seurat11$Age = "GW16"
seurat11$Age[grepl("GW10", seurat11$orig.ident)] = 'GW10'
seurat11$Age[grepl("GW12", seurat11$orig.ident)] = 'GW12'
seurat11$Age[grepl("GW14", seurat11$orig.ident)] = 'GW14'
seurat11$Age[grepl("GW23", seurat11$orig.ident)] = 'GW23'
seurat11$Age[grepl("GW8", seurat11$orig.ident)] = 'GW8'
```

```{r}
dirs = '/media/chang/HDD-12/chang/devel/goncalo/STARSolo/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
pcw = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "Goncalo")
})
pcw = merge(pcw[[1]], pcw[2:length(samples)])
pcw$Area = "Forebrain"
pcw$Sample = pcw$orig.ident
pcw$Sample[grepl("hF_WK10_2017", pcw$orig.ident)] = "hF_WK10_2017"
pcw$Sample[grepl("hF_WK10psaNCAM_2017", pcw$orig.ident)] = "hF_WK10psaNCAM_2017"
pcw$Age = "GW12"
pcw$Age[grepl("WK8", pcw$orig.ident)] = "GW10"
pcw$Age[grepl("WK8.5", pcw$orig.ident)] = "GW10.5"
pcw$Age[grepl("WK9", pcw$orig.ident)] = "GW11"
```

```{r}
dirs = '/media/chang/HDD-11/chang/gw18_spcp/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw18_layer = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW18_layer")
})
gw18_layer = merge(gw18_layer[[1]], gw18_layer[2:length(samples)])
gw18_layer$Area = "Cortex"
gw18_layer$Age = "GW18"

dirs = '/media/chang/HDD-11/chang/gw21_spcp/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw21_layer = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW21_layer")
})
gw21_layer = merge(gw21_layer[[1]], gw21_layer[2:length(samples)])
gw21_layer$Area = "Cortex"
gw21_layer$Age = "GW21"

dirs = "/media/chang/HDD-11/chang/gw20_2/Solo.out/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw20_2 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW20_2")
})
gw20_2 = merge(gw20_2[[1]], gw20_2[2:length(samples)])
gw20_2$Sample[grepl("GW20_3", gw20_2$orig.ident)] = "GW20_3"
gw20_2$Area = "Cortex"
gw20_2$Age = "GW20"

dirs = '/media/chang/HDD-9/chang/April2019NeMoSubmission/GW14/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw14 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW14_Aparna")
})
gw14 = merge(gw14[[1]], gw14[2:length(samples)])
gw14$Area = "Cortex"
gw14$Area[grepl("thalamus", gw14$orig.ident)] = "Thalamus"
gw14$Area[grepl("hypo", gw14$orig.ident)] = "Hypothalamus"
gw14$Area[grepl("GE", gw14$orig.ident)] = "GE"
gw14$Age = "GW14"

dirs = '/media/chang/HDD-9/chang/April2019NeMoSubmission/GW17/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw17 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW17_Aparna")
})
gw17 = merge(gw17[[1]], gw17[2:length(samples)])
gw17$Area = "Cortex"
gw17$Age = "GW17"

dirs = '/media/chang/HDD-9/chang/April2020NeMoSubmission/'
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw19_v3 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW19_V3")
})
gw19_v3 = merge(gw19_v3[[1]], gw19_v3[2:length(samples)])
gw19_v3$orig.ident = paste0("GW19_v3_", gw19_v3$orig.ident)
gw19_v3$Area = "Cortex"
gw19_v3$Area[grepl("Thalamus", gw19_v3$orig.ident)] = "Thalamus"
gw19_v3$Area[grepl("GE", gw19_v3$orig.ident)] = "GE"
gw19_v3$Age = "GW19"
gw19_v3 = subset(gw19_v3, subset=orig.ident != "GW19_v3_Temporal")

dirs = "/media/chang/HDD-9/chang/Jan2020_NeMoSubmission/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw18_2 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW18_2")
})
gw18_2 = merge(gw18_2[[1]], gw18_2[2:length(samples)])
gw18_2$Area = "Cortex"
gw18_2$Area[grepl("thalamus", gw18_2$orig.ident)] = "Thalamus"
gw18_2$Area[grepl("hypo", gw18_2$orig.ident)] = "Hypothalamus"
gw18_2$Area[grepl("GE", gw18_2$orig.ident)] = "GE"
gw18_2$Area[grepl("hippocampus", gw18_2$orig.ident)] = "Hippocampus"
gw18_2$Age = "GW18"

dirs = "/media/chang/HDD-9/chang/Oct2020_NeMO/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw16_v3 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW16_v3")
})
gw16_v3 = merge(gw16_v3[[1]], gw16_v3[2:length(samples)])
gw16_v3$Area = "Cortex"
gw16_v3$Area[grepl("hypo", gw16_v3$orig.ident)] = "Hypothalamus"
gw16_v3$Area[grepl("GE", gw16_v3$orig.ident)] = "GE"
gw16_v3$Age = "GW16"

dirs = "/media/chang/HDD-9/chang/January2019NeMoSubmission/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw20_twins = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW20_31")
})
gw20_twins = merge(gw20_twins[[1]], gw20_twins[2:length(samples)])
gw20_twins$Sample[grepl("34", gw20_twins$orig.ident)] = "GW20_34"
gw20_twins$Area = "Cortex"
gw20_twins$Area[grepl("cerebellum", gw20_twins$orig.ident)] = "Cerebellum"
gw20_twins$Area[grepl("GE", gw20_twins$orig.ident)] = "GE"
gw20_twins$Area[grepl("thalamus", gw20_twins$orig.ident)] = "Thalamus"
gw20_twins$Area[grepl("hypo", gw20_twins$orig.ident)] = "Hypothalamus"
gw20_twins$Age = "GW20"

dirs = "/media/chang/HDD-9/chang/cs19/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
cs19 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "CS19")
})
cs19 = merge(cs19[[1]], cs19[2:length(samples)])
cs19$Area = "Cortex"
cs19$Area[grepl("hindbrain", cs19$orig.ident)] = "Hindbrain"
cs19$Area[grepl("midbrain", cs19$orig.ident)] = "Midbrain"
cs19$Area[grepl("thalamus", cs19$orig.ident)] = "Thalamus"
cs19$Age = "GW8.5"

dirs = "/media/chang/HDD-9/chang/OctoberNeMoSubmission/raw/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
cs22 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "CS22")
})
cs22 = merge(cs22[[1]], cs22[2:length(samples)])
cs22$Area = "Cortex"
cs22$Area[grepl("hindbrain", cs22$orig.ident)] = "Hindbrain"
cs22$Area[grepl("midbrain", cs22$orig.ident)] = "Midbrain"
cs22$Area[grepl("cerebellum", cs22$orig.ident)] = "Cerebellum"
cs22$Area[grepl("GE", cs22$orig.ident)] = "GE"
cs22$Area[grepl("thalamus", cs22$orig.ident)] = "Thalamus"
cs22$Area[grepl("hypo", cs22$orig.ident)] = "Hypothalamus"
cs22$Age = "GW10"

dirs = "/media/chang/HDD-9/chang/OctoberNeMoSubmission/fastq/Solo.out/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw25 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW25")
})
gw25 = merge(gw25[[1]], gw25[2:length(samples)])
gw25$Area = "Cortex"
gw25$Area[grepl("GE", gw25$orig.ident)] = "GE"
gw25$Area[grepl("thalamus", gw25$orig.ident)] = "Thalamus"
gw25$Area[grepl("hypo", gw25$orig.ident)] = "Hypothalamus"
gw25$Age = "GW25"

dirs = "/media/chang/HDD-9/chang/JulyNeMoSubmission/Solo.out/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw20 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW20")
})
gw20 = merge(gw20[[1]], gw20[2:length(samples)])
gw20$new = gw20$orig.ident
gw20$new[gw20$orig.ident == "GW20V1"] = "GW20parietal"
gw20$new[gw20$orig.ident == "GW20somato"] = "GW20PFC"
gw20$new[gw20$orig.ident == "GW20cingulate_corpus"] = "GW20hypoventalmedial"
gw20$new[gw20$orig.ident == "GW20claustrum"] = "GW20MGE"
gw20$new[gw20$orig.ident == "GW20preoptic"] = "GW20caudalthalamus"
gw20$new[gw20$orig.ident == "GW20motor"] = "GW20CGE"
gw20$new[gw20$orig.ident == "GW20LGE"] = "GW20dorsalthalamus"
gw20$new[gw20$orig.ident == "GW20putanum"] = "GW20ventralthalamus"

gw20$new[gw20$orig.ident == "GW20parietal"] = "GW20V1"
gw20$new[gw20$orig.ident == "GW20PFC"] = "GW20somato"
gw20$new[gw20$orig.ident == "GW20hypoventalmedial"] = "GW20cingulatecorpus"
gw20$new[gw20$orig.ident == "GW20MGE"] = "GW20claustrum"
gw20$new[gw20$orig.ident == "GW20caudalthalamus"] = "GW20preoptic"
gw20$new[gw20$orig.ident == "GW20CGE"] = "GW20motor"
gw20$new[gw20$orig.ident == "GW20dorsalthalamus"] = "GW20LGE"
gw20$new[gw20$orig.ident == "GW20_ventral_thalamus"] = "GW20putanum"
gw20$orig.ident = gw20$new
gw20$new = NULL

gw20$Area = "Cortex"
gw20$Area[grepl("GE", gw20$orig.ident)] = "GE"
gw20$Area[grepl("thalamus", gw20$orig.ident)] = "Thalamus"
gw20$Area[grepl("hypo", gw20$orig.ident)] = "Hypothalamus"
gw20$Age = "GW20"

dirs = "/media/chang/HDD-9/chang/AprilNeMoSubmission/gw/Solo.out/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw22t = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW22T")
})
gw22t = merge(gw22t[[1]], gw22t[2:length(samples)])
gw22t$Sample[grepl("GW22_", gw22t$orig.ident)] = "GW22"
gw22t$Area = "Cortex"
gw22t$Area[grepl("GE", gw22t$orig.ident)] = "GE"
gw22t$Area[grepl("thalamus", gw22t$orig.ident)] = "Thalamus"
gw22t$Area[grepl("hypo", gw22t$orig.ident)] = "Hypothalamus"
gw22t$Age = "GW22"

dirs = "/media/chang/HDD-11/chang/gw20_2018/Solo.out/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw20_3 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW20_3")
})
gw20_3 = merge(gw20_3[[1]], gw20_3[2:length(samples)])
gw20_3$Sample[grepl("GW20_3", gw20_3$orig.ident)] = "GW20_3"
gw20_3$orig.ident[gw20_3$orig.ident == "GW20_cingulate"] = "GW20_3_cingulate"
gw20_3$orig.ident[gw20_3$orig.ident == "GW20_temporal"] = "GW20_3_temporal"
gw20_3$Area = "Cortex"
gw20_3$Age = "GW20"

dirs = "/media/chang/HDD-9/chang/AprilNeMoSubmission/cs/Solo.out/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
cs20 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "CS20")
})
cs20 = merge(cs20[[1]], cs20[2:length(samples)])
cs20$Area = "Cortex"
cs20$Area[grepl("midbrain", cs20$orig.ident)] = "Midbrain"
cs20$Area[grepl("cerebellum", cs20$orig.ident)] = "Cerebellum"
cs20$Area[grepl("thalamus", cs20$orig.ident)] = "Thalamus"
cs20$Area[grepl("hypo", cs20$orig.ident)] = "Hypothalamus"
cs20$Age = "GW9"

dirs = "/media/chang/HDD-9/chang/cellrangeroutputs/GW14_Solo.out/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw14_2 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW14_2")
})
gw14_2 = merge(gw14_2[[1]], gw14_2[2:length(samples)])
gw14_2$Sample[gw14_2$orig.ident == "GW14"] = "GW14_3"
gw14_2$Area = "Cortex"
gw14_2$Area[grepl("GE", gw14_2$orig.ident)] = "GE"
gw14_2$Age = "GW14"

dirs = "/media/chang/HDD-9/chang/cellrangeroutputs/GW18_Solo.out/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw18 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW18")
})
gw18 = merge(gw18[[1]], gw18[2:length(samples)])
gw18$Area = "Cortex"
gw18$Area[grepl("GE", gw18$orig.ident)] = "GE"
gw18$Area[grepl("thalamus", gw18$orig.ident)] = "Thalamus"
gw18$Area[grepl("hypo", gw18$orig.ident)] = "Hypothalamus"
gw18$Area[grepl("hippo", gw18$orig.ident)] = "Hippocampus"
gw18$Age = "GW18"

dirs = "/media/chang/HDD-9/chang/cellrangeroutputs/GW19_Solo.out/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw19 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW19")
})
gw19 = merge(gw19[[1]], gw19[2:length(samples)])
gw19$orig.ident[gw19$orig.ident == "GW19_hippocampu"] = "GW19_hippocampus"
gw19$Area = "Cortex"
gw19$Area[grepl("GE", gw19$orig.ident)] = "GE"
gw19$Area[grepl("hippo", gw19$orig.ident)] = "Hippocampus"
gw19$Age = "GW19"
gw19$Sample[gw19$orig.ident == "GW19"] = "GW19_2"

dirs = "/media/chang/HDD-9/chang/deeper10X_runs/CS20_Solo.out/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
cs20_2 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "CS20_2")
})
cs20_2 = merge(cs20_2[[1]], cs20_2[2:length(samples)])
cs20_2$Area = "Cortex"
cs20_2$Area[grepl("cerebellum", cs20_2$orig.ident)] = "Cerebellum"
cs20_2$Area[grepl("midbrain", cs20_2$orig.ident)] = "Midbrain"
cs20_2$Area[grepl("hypo", cs20_2$orig.ident)] = "Hypothalamus"
cs20_2$Age = "GW9"

dirs = "/media/chang/HDD-9/chang/Jan2018_progressdata_scRNAseq/161228_D00328_0598_AH7JJVBCXY_fastqs/kriegsteina-10x-v2-pool/Solo.out/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
cs22_3 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "CS22_3")
})
cs22_3 = merge(cs22_3[[1]], cs22_3[2:length(samples)])
cs22_3$Sample = "CS22_4"
cs22_3 = subset(cs22_3, subset=orig.ident == "CS22_Thalamus")
cs22_3 = merge(cs22_3, cs22_4)
cs22_3$Sample[cs22_3$Sample == "CS22_4"] = "CS22_3"
cs22_3$Area = "Cortex"
cs22_3$Area[grepl("cerebellum", cs22_3$orig.ident)] = "Cerebellum"
cs22_3$Area[grepl("midbrain", cs22_3$orig.ident)] = "Midbrain"
cs22_3$Area[grepl("GE", cs22_3$orig.ident)] = "GE"
cs22_3$Area[grepl("hindbrain", cs22_3$orig.ident)] = "Hindbrain"
cs22_3$Area[grepl("Thalamus", cs22_3$orig.ident)] = "Thalamus"
cs22_3$Area[grepl("hypo", cs22_3$orig.ident)] = "Hypothalamus"
cs22_3 = subset(cs22_3, subset=Sample == "CS22_3")
cs22_3$Age = "GW10"

dirs = "/media/chang/HDD-9/chang/Jan2018_progressdata_scRNAseq/170314_D00328_0625_BCABUNANXX_fastqs/Solo.out/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw19_2 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW19")
})
gw19_2 = merge(gw19_2[[1]], gw19_2[2:length(samples)])
gw19_2$Area = "Cortex"
gw19_2$Area[grepl("GE", gw19_2$orig.ident)] = "GE"
gw19_2$Area[grepl("hippocampus", gw19_2$orig.ident)] = "Hippocampus"
gw19_2$Area[grepl("thalamus", gw19_2$orig.ident)] = "Thalamus"
gw19_2$Area[grepl("hypo", gw19_2$orig.ident)] = "Hypothalamus"
gw19_2$Age = "GW19"
gw19_2 = subset(gw19_2, subset=orig.ident %in% c("GW19_hypothalamus","GW19_M1_CP",
                                                 "GW19_Temp_all","GW19_thalamus",
                                                 "GW19_V1_CP"))
gw19 = merge(gw19, gw19_2)
rm(gw19_2)

dirs = "/media/chang/HDD-11/chang/gw30/Solo.out/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw30 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW30")
})
gw30 = merge(gw30[[1]], gw30[2:length(samples)])
gw30$Area = "Cortex"
gw30$Area[gw30$orig.ident == 'GW30_GE'] = "GE"
gw30$Age = "GW30"

dirs = "/media/chang/HDD-9/chang/deeper10X_runs/CS22_Solo.out/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
cs22_4 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "CS22_4")
})
cs22_4 = merge(cs22_4[[1]], cs22_4[2:length(samples)])
cs22_4$Sample[grepl("CS22_2", cs22_4$orig.ident)] = "CS22_2"
cs22_4$Area = "Cortex"
cs22_4$Area[grepl("GE", cs22_4$orig.ident)] = "GE"
cs22_4$Area[grepl("cerebellum", cs22_4$orig.ident)] = "Cerebellum"
cs22_4$Area[grepl("thalamus", cs22_4$orig.ident)] = "Thalamus"
cs22_4$Area[grepl("hindbrain", cs22_4$orig.ident)] = "Hindbrain"
cs22_4$Area[grepl("midbrain", cs22_4$orig.ident)] = "Midbrain"
cs22_4$Area[grepl("hypo", cs22_4$orig.ident)] = "Hypothalamus"
cs22_4$Age = "GW10"
cs22_4 = subset(cs22_4, subset=Sample == "CS22_4")
cs22_3 = merge(cs22_3, cs22_4)
rm(cs22_4)  
cs22_3$Area[grepl("Thalamus", cs22_3$orig.ident)] = "Thalamus"

save.image("/media/chang/HDD-9/chang/samples.RData")
```
```
dirs = "/media/chang/HDD-9/chang/Jan2018_progressdata_scRNAseq/170414_D00328_0641_ACAUFRANXX/Solo.out/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw18_3 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW18_3")
})
gw18_3 = merge(gw18_3[[1]], gw18_3[2:length(samples)])
gw18_3$Area = "Cortex"
gw18_3$Area[grepl("GE", gw18_3$orig.ident)] = "GE"
gw18_3$Area[grepl("hippocampus", gw18_3$orig.ident)] = "Hippocampus"
gw18_3$Area[grepl("thalamus", gw18_3$orig.ident)] = "Thalamus"
gw18_3$Area[grepl("hypo", gw18_3$orig.ident)] = "Hypothalamus"

dirs = "/media/chang/HDD-9/chang/Jan2018_progressdata_scRNAseq/170627_D00328_0666_ACBBP4ANXX_fastqs/Solo.out/"
setwd(dirs)
dir = list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
samples = str_sub(dir,1,nchar(dir)-9)
gw18_4 = lapply(c(1:length(samples)), function(i){
  ReadSTAR(paste0(dirs,dir[[i]],"/"), proj = samples[[i]], sample = "GW18_4")
})
gw18_4 = merge(gw18_4[[1]], gw18_4[2:length(samples)])
gw18_4$Area = "Cortex"
gw18_4$Area[grepl("GE", gw18_4$orig.ident)] = "GE"
gw18_4$Area[grepl("hippocampus", gw18_4$orig.ident)] = "Hippocampus"
gw18_4$Area[grepl("thalamus", gw18_4$orig.ident)] = "Thalamus"
gw18_4$Area[grepl("hypo", gw18_4$orig.ident)] = "Hypothalamus"
```
```{r}
merged = merge(seurat, c(seurat2,seurat3,seurat4,seurat5,seurat6,seurat7,seurat8,
                         seurat9,seurat10,seurat11,pcw,cs19,cs20,cs20_2))
rm(seurat);rm(seurat2);rm(seurat3);rm(seurat4);rm(seurat5);rm(seurat6);rm(seurat7);rm(seurat8);rm(seurat9);rm(seurat10);rm(seurat11);rm(pcw);rm(cs19);rm(cs20);rm(cs20_2);gc()

merged2 = merge(cs22,c(cs22_3,gw14,gw14_2,gw16_v3,gw17,gw18,gw18_2,gw18_layer,gw19,gw19_v3))
rm(cs22);rm(cs22_3);rm(gw14);rm(gw14_2);rm(gw16_v3);rm(gw17);rm(gw18);rm(gw18_2);rm(gw18_layer);rm(gw19);rm(gw19_v3);gc()

merged3 = merge(gw20,c(gw20_2,gw20_3,gw20_twins,gw21_layer,gw22t,gw25,gw30))
rm(gw20);rm(gw20_2);rm(gw20_3);rm(gw20_twins);rm(gw21_layer);rm(gw22t);rm(gw25);rm(gw30);gc()

saveRDS(list(merged, merged2,merged3), file='/media/chang/HDD-9/chang/merged.rds')

tmp = as.SingleCellExperiment(merged)
merged = merge(merged, c(merged2,merged3))
```

```{r}
thal = subset(merged, subset=Area=="Thalamus")
thal2 = subset(merged2, subset=Area=="Thalamus")
thal3 = subset(merged3, subset=Area=="Thalamus")
thal = merge(thal, c(thal2, thal3))
saveRDS(thal,"/media/chang/HDD-9/chang/thal_raw.rds")

mtx = thal@assays$RNA@counts[!grepl("MT-",rownames(thal@assays$RNA@counts)),]
mtx = mtx[!grepl("RPS",rownames(mtx)),]
mtx = mtx[!grepl("RPL",rownames(mtx)),]
mtx = mtx[!grepl("ENSG",rownames(mtx)),]
mtx = mtx[!grepl("MIR",rownames(mtx)),]
mtx = mtx[!grepl("LINC",rownames(mtx)),]
mtx = mtx[!grepl("FOS",rownames(mtx)),]
mtx = mtx[!grepl("JUN",rownames(mtx)),]
mtx = mtx[!grepl("HSPA",rownames(mtx)),]
mtx = mtx[!grepl("MALAT1",rownames(mtx)),]
mtx = mtx[!grepl("-AS",rownames(mtx)),]

thal2 = CreateSeuratObject(mtx, meta.data = thal@meta.data)
thal2 = subset(thal2, subset=nFeature_RNA >= 500 & nCount_RNA >= 800)
saveRDS(thal2,"/media/chang/HDD-9/chang/thal_raw_filtered_genes.rds")

######

ge = subset(merged, subset=Area %in% c("GE","LGE","CGE","MGE"))

ge2 = subset(merged2, subset=Area=="GE")
unique(merged2$orig.ident[grepl("ar", merged2$orig.ident)])
cells = colnames(merged2)[grepl("ar", merged2$orig.ident)]
par2 = subset(merged2, cells=cells)

ge3 = subset(merged3, subset=Area=="GE")
unique(merged3$orig.ident[grepl("ar", merged3$orig.ident)])
cells = colnames(merged3)[grepl("ar", merged3$orig.ident)]
par3 = subset(merged3, cells=cells)
par3 = subset(par3, subset=orig.ident=="GW25_pulminarthal", invert=T)

ge = merge(ge, c(ge2, par2, ge3, par3))
rm(ge2);rm(ge3);rm(par2);rm(par3);gc()

mtx = ge@assays$RNA@counts[!grepl("MT-",rownames(ge@assays$RNA@counts)),]
mtx = mtx[!grepl("RPS",rownames(mtx)),]
mtx = mtx[!grepl("RPL",rownames(mtx)),]
mtx = mtx[!grepl("ENSG",rownames(mtx)),]
mtx = mtx[!grepl("MIR",rownames(mtx)),]
mtx = mtx[!grepl("LINC",rownames(mtx)),]
mtx = mtx[!grepl("FOS",rownames(mtx)),]
mtx = mtx[!grepl("JUN",rownames(mtx)),]
mtx = mtx[!grepl("HSPA",rownames(mtx)),]
mtx = mtx[!grepl("MALAT1",rownames(mtx)),]
mtx = mtx[!grepl("-AS",rownames(mtx)),]

ge2 = CreateSeuratObject(mtx, meta.data = ge@meta.data)
ge3 = CreateSeuratObject(ge2@assays$RNA@counts)
ge2$nCount_RNA = ge3$nCount_RNA
ge2$nFeature_RNA = ge3$nFeature_RNA
rm(ge3);gc()
ge2 = subset(ge2, subset=nFeature_RNA >= 500 & nCount_RNA >= 800);gc()
saveRDS(ge2,"/media/chang/HDD-9/chang/ge_raw_filtered_genes.rds")


```

```{r}
mid = subset(merged[[1]], subset=Area=="Midbrain")
mid2 = subset(merged[[2]], subset=Area=="Midbrain")
mid = merge(mid, mid2)
saveRDS(mid,"/media/chang/HDD-9/chang/mid_raw.rds")

mtx = mid@assays$RNA@counts[!grepl("MT-",rownames(mid@assays$RNA@counts)),]
mtx = mtx[!grepl("RPS",rownames(mtx)),]
mtx = mtx[!grepl("RPL",rownames(mtx)),]
mtx = mtx[!grepl("ENSG",rownames(mtx)),]
mtx = mtx[!grepl("MIR",rownames(mtx)),]
mtx = mtx[!grepl("LINC",rownames(mtx)),]
mtx = mtx[!grepl("FOS",rownames(mtx)),]
mtx = mtx[!grepl("JUN",rownames(mtx)),]
mtx = mtx[!grepl("HSPA",rownames(mtx)),]
mtx = mtx[!grepl("MALAT1",rownames(mtx)),]
mtx = mtx[!grepl("-AS",rownames(mtx)),]

mid2 = CreateSeuratObject(mtx, meta.data = mid@meta.data)
mid2 = subset(mid2, subset=nFeature_RNA >= 500 & nCount_RNA >= 800)
saveRDS(mid2,"/media/chang/HDD-9/chang/mid_raw_filtered_genes.rds")

```