---
title: "STG"
output: html_notebook
---

```{r}
library(Seurat)
library(dittoSeq)
library(harmony)
library(SeuratWrappers)
library(scCustomize)
library(scds)
library(presto)
library(viridis)
library(stringr)
library(FastCAR)
library(Matrix)
library(DropletQC)
library(SingleCellExperiment)

ReadSTAR <- function(data.dir, proj = "SeuratObject", feats = 1000, ratio=.1,
                     counts = 1500, sample="Sample", doublet=TRUE) {
  data.dir.genefull = paste0(data.dir, "GeneFull_Ex50pAS/raw")
  mtx = file.path(data.dir.genefull, "UniqueAndMult-EM.mtx")
  cells = file.path(data.dir.genefull, "barcodes.tsv")
  features = file.path(data.dir.genefull, "features.tsv")
  raw = ReadMtx(mtx = mtx, cells = cells, features = features)
  
  seurat = CreateSeuratObject(raw, project=proj, min.features = feats)
  
  data.dir.velo = paste0(data.dir, "/Velocyto/raw")
  cells = file.path(data.dir.velo, "barcodes.tsv")
  features = file.path(data.dir.velo, "features.tsv")
  spliced = file.path(data.dir.velo, "spliced.mtx")
  unspliced = file.path(data.dir.velo, "unspliced.mtx")
  ambi = file.path(data.dir.velo, "ambiguous.mtx")
  spliced = ReadMtx(mtx = spliced, cells = cells, features = features)
  unspliced = ReadMtx(mtx = unspliced, cells = cells, features = features)
  ambi = ReadMtx(mtx = ambi, cells = cells, features = features)
  spliced = spliced + ambi

  seurat[['unspliced']] = CreateAssayObject(unspliced[,colnames(seurat)])
  seurat[['spliced']] = CreateAssayObject(spliced[,colnames(seurat)])
  seurat$droplet_qc_ratio = seurat$nCount_unspliced / seurat$nCount_RNA

  md = seurat@meta.data[,c("droplet_qc_ratio","nCount_RNA" )]
  md$nCount_RNA = as.integer(md$nCount_RNA)
  
  calls = identify_empty_drops(md, nf_rescue = ratio, umi_rescue=counts)
  seurat$cell_status = calls$cell_status

  seurat = subset(seurat, subset=cell_status == "cell")

  ambProfile = describe.ambient.RNA.sequence(fullMatrix = raw, 
                                             start = 10, 
                                             stop = 200, 
                                             by = 10, 
                                             contaminationChanceCutoff = 0.05)
  emptyDropletCutoff = recommend.empty.cutoff(ambProfile)
  ambientProfile = determine.background.to.remove(raw, emptyDropletCutoff, .05)
  seurat[['cleaned']] = CreateAssayObject(remove.background(seurat@assays$RNA@counts, ambientProfile))
  
  sce = cxds_bcds_hybrid(SingleCellExperiment(list(counts=seurat@assays$cleaned@counts)))
  seurat$hybrid_score = sce$hybrid_score

  seurat[['percent.mt']] = PercentageFeatureSet(seurat, pattern = "MT-",assay = 'cleaned')
  
  if(doublet == TRUE){
    n_cells = dim(seurat)[2]
    if (n_cells >= 15000){
      seurat = subset(seurat, subset=percent.mt <= 20 & hybrid_score < 1)
    } else if(n_cells >= 10000){
      seurat = subset(seurat, subset=percent.mt <= 20 & hybrid_score < 1.25)
    } else if(n_cells >= 5000){
      seurat = subset(seurat, subset=percent.mt <= 20 & hybrid_score < 1.5)
    } else if(n_cells < 5000){
      seurat = subset(seurat, subset=percent.mt <= 20 & hybrid_score < 1.75)
    }
  } else{
    seurat = subset(seurat, subset=percent.mt <= 20)
  }
  seurat$Sample = sample
  return(seurat)
}
```

```{r}
dirs = '/media/chang/HDD-10/chang/stg/astg_Solo.out/'
seurat = ReadSTAR(dirs, proj = "aSTG", sample = "aSTG")

dirs = '/media/chang/HDD-10/chang/stg/pstg_Solo.out/'
seurat2 = ReadSTAR(dirs, proj = "pSTG", sample = "pSTG")

dirs = '/media/chang/HDD-10/chang/stg/mstg_Solo.out/'
seurat3 = ReadSTAR(dirs, proj = "mSTG", sample = "mSTG")

dirs = '/media/chang/HDD-10/chang/stg/e37_Solo.out/'
seurat4 = ReadSTAR(dirs, proj = "e37", sample = "e37")

dirs = '/media/chang/HDD-10/chang/stg/e41_Solo.out/'
seurat5 = ReadSTAR(dirs, proj = "e41", sample = "e41")

dirs = '/media/chang/HDD-10/chang/stg/e45_Solo.out/'
seurat6 = ReadSTAR(dirs, proj = "e45", sample = "e45")

dirs = '/media/chang/HDD-10/chang/stg/e60_Solo.out/'
seurat7 = ReadSTAR(dirs, proj = "e60", sample = "e60")

dirs = '/media/chang/HDD-10/chang/stg/e61_Solo.out/'
seurat8 = ReadSTAR(dirs, proj = "e61", sample = "e61")

dirs = '/media/chang/HDD-10/chang/stg/e76_Solo.out/'
seurat9 = ReadSTAR(dirs, proj = "e76", sample = "e76")
```

```{r}
stg = merge(seurat, c(seurat2,seurat3,seurat4,seurat5,seurat6,seurat7,seurat8,seurat9))

saveRDS(stg, file="/media/chang/HDD-10/chang/stg/stg.rds")

stg = SCTransform(stg, vst.flavor='v2', assay = 'cleaned')
stg = RunPCA(stg)
stg = RunUMAP(stg, dims=1:20)

stg$Sample[grepl('e', stg$Sample)] = 'eSTG'

sten = readRDS("/media/chang/HDD-10/chang/stg/sten.rds")
sten$Sample = sten$development_stage
sten[['cleaned']] = sten[['RNA']]
sten$nCount_cleaned = sten$total_UMIs
sten$nFeature_cleaned = sten$total_genes
merged_stg = merge(stg, sten)

saveRDS(merged_stg, file="/media/chang/HDD-10/chang/stg/merged.rds")

```


```{r}
merged_stg = SCTransform(merged_stg, vst.flavor='v2', assay = 'cleaned')


```



```{r}
stg = readRDS("/media/chang/HDD-3/chang/stg/sten.rds")
stg = FindNeighbors(stg, dims=1:2, reduction = 'UMAP')
stg = FindClusters(stg, algorithm = 2, resolution = .1)
DimPlot(stg, label=T, cols=dittoColors(), group.by = 'RNA_snn_res.0.1')+
  DimPlot(stg, label=T, group.by = "supercluster_term", cols=dittoColors()) & NoAxes()
test = wilcoxauc(stg, group_by = "RNA_snn_res.0.1")
top_markers(test)

ensembl <- useMart("ensembl", dataset="hsapiens_gene_ensembl")
bm <- getBM(attributes=c("ensembl_gene_id", "hgnc_symbol"), values=rownames(stg), mart=ensembl)
bm = bm[bm$hgnc_symbol != "",]
bm = bm[!duplicated(bm$ensembl_gene_id),]
rownames(bm) = bm$ensembl_gene_id
bm = bm[intersect(bm$ensembl_gene_id, rownames(stg@assays$RNA@data)),]
mtx = stg@assays$RNA@data[bm$ensembl_gene_id,]
rownames(mtx) = bm$hgnc_symbol
stg2 = CreateSeuratObject(mtx)
stg2@meta.data = cbind(stg2@meta.data, stg@meta.data)
stg2[["UMAP"]] = stg[["UMAP"]]
stg2[["tSNE"]] = stg[["tSNE"]]
saveRDS(stg2, file='/media/chang/HDD-3/chang/stg/sten_cleaned.rds')

FeaturePlot(stg, features = c("ENC1","CBLN2","TRHDE"), order=T, max.cutoff = 'q99') & NoAxes()

stg = subset(stg, idents=1:26)
library(DropletUtils)
write10xCounts("/media/chang/HDD-3/chang/stg/sten_cleaned.h5",stg@assays$RNA@counts,
              version='3', type="HDF5")
av.exp <- AverageExpression(stg)$RNA
cor.exp <- as.data.frame(cor(av.exp))
pheatmap(cor.exp)

```