---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(dittoSeq)
library(harmony)
library(SeuratWrappers)
library(scCustomize)
library(scds)
library(presto)
library(viridis)
library(stringr)
library(scRNAtoolVis)
```

```{r}
options(future.globals.maxSize= 8912896000)

thal = readRDS("/media/chang/HDD-8/chang/aparna/thal.rds")

thal = SCTransform(thal, vst.flavor='v2', assay = "cleaned")

saveRDS(thal,"/media/chang/HDD-8/chang/aparna/thal.rds")

VariableFeatures(thal)[grepl("MT-", VariableFeatures(tha))]


thal = RunPCA(thal)
thal = RunHarmony(thal, group.by.vars = 'Sample', plot_convergence = T)
thal = RunUMAP(thal, dims=1:50, reduction = 'harmony')
thal = FindNeighbors(thal, dims=1:50, reduction = 'harmony')
thal = FindClusters(thal, resolution = .6, algorithm = 2)

thal$SubArea = "Thalamus"
thal$SubArea[grepl("dorsal",thal$orig.ident)] = "Dorsal"
thal$SubArea[grepl("ventral",thal$orig.ident)] = "Ventral"
thal$SubArea[grepl("caudal",thal$orig.ident)] = "Caudal"

thal$Sex = "M"
thal$Sex[thal$Sample == "CS19"] = "F"
thal$Sex[thal$Sample == "CS22_3"] = "F"
thal$Sex[thal$Sample == "GW14_Aparna"] = "F"
thal$Sex[thal$Sample == "GW22T"] = "F"

saveRDS(thal, file="/media/chang/HDD-9/chang/thal_gps.rds")

markers = wilcoxauc(thal2,seurat_assay = 'SCT')
top_markers(markers)

Idents(thal) = thal$SCT_snn_res.0.6
area = FindMarkers(thal, subset.ident = 4, group.by = 'SubArea',ident.1 = 'Ventral',ident.2 = 'Dorsal')
head(area[order(area$avg_log2FC, decreasing = T),], 20)
area_genes = c("FTH1","S100A6","LSAMP","PCDH9","SNTG1",
               "ROBO2","NEFL","RBP1","PENK","CALB1","CDH9","CD247")

area2 = FindMarkers(thal, subset.ident = 6, group.by = 'SubArea',ident.1 = 'Ventral',ident.2 = 'Dorsal')
head(area2[order(area2$avg_log2FC, decreasing = T),], 20)
area_genes2 = c("PKIB","TAC1")

area3 = FindMarkers(thal, ident.1 = '30', only.pos = T,min.diff.pct = .25)
head(area3[order(area3$avg_log2FC, decreasing = T),], 20)
area_genes3 = c("CALB2", "TCF7L2")

crabp1 = FindMarkers(thal, ident.1 = '32', only.pos = T,min.diff.pct = .25)
head(crabp1[order(crabp1$avg_log2FC, decreasing = T),], 20)
crabp1_genes = c("CRABP1","ST18","TAC3")

epend_genes = c("RSPH1","FOXJ1","GFAP","CRYAB")

genes = c(area_genes, area_genes2, area_genes3, crabp1_genes, epend_genes,
          "MRC1","AIF1","P2RY12","CLDN5","DCN","DLC1","MKI67","SOX6","PTPRZ1",
          "AQP4","SOX4","VIM","SST",'TXN')
```

```{r}
thal = readRDS("/media/chang/HDD-8/chang/aparna/thal.rds")
first = subset(thal, subset=Sample %in% c("CS12","CS14","CS15","CS19","CS22","CS22_2"))
first = subset(first, subset=Sample=="CS19", invert=T)
first = SCTransform(first, vst.flavor='v2', assay='cleaned', variable.features.n = 2000)

VariableFeatures(first) = VariableFeatures(first)[!grepl("MT-", VariableFeatures(first))]
VariableFeatures(first) = VariableFeatures(first)[!grepl("MALAT1", VariableFeatures(first))]
VariableFeatures(first) = VariableFeatures(first)[!grepl("RPS", VariableFeatures(first))]
VariableFeatures(first) = VariableFeatures(first)[!grepl("RPL", VariableFeatures(first))]

VariableFeaturePlot_scCustom(first, num_features = 2000) & ylim(0,3)

first = RunPCA(first, npcs=20)
first = RunHarmony(first, group.by.vars='Sample', assay.use = "SCT")
first = RunUMAP(first, dims=1:20, reduction='harmony')
first = FindNeighbors(first, dims=1:20, reduction='harmony')

first = FindClusters(first, algorithm = 2, resolution = 1)


FeaturePlot(first, order=T,max.cutoff='q95', ncol=4,
            features = c("TCF7L2","MKI67","MEIS2","ASCL1","FOXG1","SHH","NKX2-2","HES1","ISL1","OLIG3","OLIG2","GSX2","SIX3","GAD2","GATA3","LHX1")) & NoAxes() & scale_color_viridis()


first$clusters = as.character(first$SCT_snn_res.1)
first$clusters[first$clusters == 9] = "MES"
first$clusters[first$clusters == 19] = "MES"
first$clusters[first$clusters == 1] = "NPC1"
first$clusters[first$clusters == 0] = "NPC1"
first$clusters[first$clusters == 6] = "NPC1"
first$clusters[first$clusters == 4] = "nIPC1"
first$clusters[first$clusters == 7] = "IPC1"
first$clusters[first$clusters == 17] = "IPC1"
first$clusters[first$clusters == 10] = "EN1"
first$clusters[first$clusters == 11] = "EN1"
first$clusters[first$clusters == 13] = "IN1"
first$clusters[first$clusters == 15] = "IN2"
first$clusters[first$clusters == 16] = "IN3"
first$clusters[first$clusters == 23] = "RBC"
first$clusters[first$clusters == 14] = "NPC3"
first$clusters[first$clusters == 22] = "nIPC2"
first$clusters[first$clusters == 21] = "IPC2"
first$clusters[first$clusters == 3] = "EN2"
first$clusters[first$clusters == 5] = "nEN1"
first$clusters[first$clusters == 18] = "nEN1"
first$clusters[first$clusters == 20] = "nEN1"
first$clusters[first$clusters == 8] = "nEN2"
first$clusters[first$clusters == 2] = "NPC2"
first$clusters[first$clusters == 12] = "NPC2"

Idents(first) = first$clusters
saveRDS(first, file='/media/chang/HDD-8/chang/aparna/first.rds')


DimPlot_scCustom(first, group.by = 'Sample')
DimPlot_scCustom(first, label=T)

FeaturePlot(first, features = c("TCF7L2","MKI67","MEIS2","GAD2"), order=T,max.cutoff='q98') & NoAxes() & scale_color_viridis()

saveRDS(first, file='/media/chang/HDD-8/chang/aparna/first.rds')
```

```{r}
seuratToH5AD <- function(seuratObj, h5ad_output, pca=FALSE, umap=TRUE, harmony=TRUE){
  Sys.setenv(RETICULATE_PYTHON = "/home/chang/miniconda3/envs/venv/bin/python")
  library(reticulate)
  #use_condaenv('venv')
  library(Matrix)
  writeMM(t(seuratObj@assays$cleaned@counts), file='combined.mtx')
  writeMM(t(seuratObj@assays$spliced@counts), file='spliced.mtx')
  writeMM(t(seuratObj@assays$unspliced@counts), file='unspliced.mtx')
  write.csv(rownames(seuratObj@assays$spliced@counts), file = "genes.csv", row.names = FALSE)
  if(umap == TRUE){
  	write.csv(seuratObj@reductions$umap@cell.embeddings, file = "umap.csv", row.names = FALSE)
  }
  if(pca == TRUE){
	  write.csv(seuratObj@reductions$pca@cell.embeddings, file = "pca.csv", row.names = FALSE)
  }
  if(harmony == TRUE){
	  write.csv(seuratObj@reductions$harmony@cell.embeddings, file = "harmony.csv", row.names= FALSE)
  }
  write.csv(colnames(seuratObj@assays$spliced@counts), file = "cells.csv", row.names = FALSE)
  write.csv(seuratObj@meta.data, file = "meta.csv", row.names = FALSE)
  source_python('~/build.py')
  build(h5ad_output, pca = pca, umap = umap, harmony = harmony)
  #file.remove('combined.mtx')
  file.remove('spliced.mtx')
  file.remove('unspliced.mtx')
  file.remove('genes.csv')
  file.remove('cells.csv')
  if(umap == TRUE){
  	file.remove('umap.csv')
  }
  if(pca == TRUE){
	  file.remove('pca.csv')
  }
  if(harmony == TRUE){
	  file.remove('harmony.csv')
  }
  file.remove('meta.csv')
}
```

```{r}
first = readRDS("/media/chang/HDD-8/chang/aparna/first.rds")

setwd("/media/chang/HDD-8/chang/aparna/")
seuratToH5AD(seuratObj = first, h5ad_output = "first.h5ad")





first_in = subset(first, idents=c("IN_NPC1","IN_NPC2","IN1","IN2","IN3"))

cds <- as.cell_data_set(first_in)
cds <- cluster_cells(cds)
plot_cells(cds, color_cells_by = "partition", show_trajectory_graph = FALSE)

cds <- learn_graph(cds)
plot_cells(cds, label_groups_by_cluster = FALSE, label_leaves = FALSE, label_branch_points = FALSE)

max.foxg1 <- which.max(unlist(FetchData((first_in), "ASCL1")))
max.foxg1 <- colnames((first_in))[max.foxg1]
cds <- order_cells(cds, root_cells = max.foxg1)
plot_cells(cds, color_cells_by = "pseudotime", label_cell_groups = FALSE, label_leaves = FALSE, 
    label_branch_points = FALSE)
first_in$pseudotime = pseudotime(cds)
FeaturePlot(first_in, features = 'pseudotime', order=T, max.cutoff = 'q99') + scale_color_viridis()



first_en = subset(first, idents=c("EN_NPC1","EN_NPC2","EN_NPC3","EN_NPC4","EN1","EN2","nEN"))

cds <- as.cell_data_set(first_en)
cds <- cluster_cells(cds)
plot_cells(cds, color_cells_by = "partition", show_trajectory_graph = FALSE)

cds <- learn_graph(cds)
plot_cells(cds, label_groups_by_cluster = FALSE, label_leaves = FALSE, label_branch_points = FALSE)

max.foxg1 <- which.max(unlist(FetchData((first_en), "FOXG1")))
max.foxg1 <- colnames((first_en))[max.foxg1]
cds <- order_cells(cds, root_cells = max.foxg1)
plot_cells(cds, color_cells_by = "pseudotime", label_cell_groups = FALSE, label_leaves = FALSE, 
    label_branch_points = FALSE)
first_en$pseudotime = pseudotime(cds)


first$pseudotime = 0
first$pseudotime[colnames(first_en)] = first_en$pseudotime
first$pseudotime[colnames(first_in)] = first_in$pseudotime

DefaultAssay(first) = 'cleaned'
first = NormalizeData(first)

FeatureScatter(first_en, feature1 = "pseudotime", feature2 = "FOXG1", pt.size = .5, 
               cols=dittoColors()) + geom_smooth(method = "loess", se = F, span = 2,size=2,
                                                 aes(color = first_en$SCT_snn_res.0.5))
FeatureScatter(first_en, feature1 = "pseudotime", feature2 = "HES1", pt.size = .5, 
               cols=dittoColors()) + geom_smooth(method = "loess", se = F, span = 2,size=2,
                                                 aes(color = first_en$SCT_snn_res.0.5))
FeatureScatter(first_en, feature1 = "pseudotime", feature2 = "WNT2B", pt.size = .5, 
               cols=dittoColors()) + geom_smooth(method = "loess", se = F, span = 2,size=2,
                                                 aes(color = first_en$SCT_snn_res.0.5))

FeatureScatter(first_in, feature1 = "pseudotime", feature2 = "OLIG3", pt.size = .5, 
               cols=dittoColors()) + geom_smooth(method = "loess", se = F, span = 2,size=2,
                                                 aes(color = first_in$SCT_snn_res.0.5))
FeatureScatter(first_in, feature1 = "pseudotime", feature2 = "GATA3", pt.size = .5, 
               cols=dittoColors()) + geom_smooth(method = "loess", se = F, span = 2,size=2,
                                                 aes(color = first_in$SCT_snn_res.0.5))
FeatureScatter(first_in, feature1 = "pseudotime", feature2 = "ASCL1", pt.size = .5, 
               cols=dittoColors()) + geom_smooth(method = "loess", se = F, span = 2,size=2,
                                                 aes(color = first_in$SCT_snn_res.0.5))
FeatureScatter(first_in, feature1 = "pseudotime", feature2 = "SHH", pt.size = .5, 
               cols=dittoColors()) + geom_smooth(method = "loess", se = F, span = 2,size=2,
                                                 aes(color = first_in$SCT_snn_res.0.5))
```

```{r}
first = readRDS("/media/chang/HDD-8/chang/aparna/first.rds")

color = dittoColors()[1:length(unique(Idents(first)))]
names(color) = levels(first)

pdf("/media/chang/HDD-8/chang/aparna/pdfs/first_dimplot.pdf")
SCpubr::do_DimPlot(sample = first, label = T, 
                   colors.use = color)
dev.off()

deg <- tibble::tibble(markers)
deg = deg[!grepl("MT-",deg$gene),]
deg = deg[!grepl("RPS",deg$gene),]
deg = deg[!grepl("RPL",deg$gene),]
SCpubr::do_GroupwiseDEPlot(sample = first,
                           de_genes = deg, top_genes = 4)

library(readxl)
mouse_markers <- lapply(1:23, function(i) read_excel("~/thal_table.xlsx", sheet = i))
names(mouse_markers) = openxlsx::getSheetNames("~/thal_table.xlsx")
sigs = lapply(mouse_markers, function(i){
  genes = toupper(i$Gene[1:100])
  intersect(genes, rownames(first))[1:15]
})

pdf("/media/chang/HDD-3/chang/dapi/first_bar_age.pdf")
SCpubr::do_BarPlot(first, group.by = "Age", 
                         split.by = "clusters",
                         plot.title = "Number of cells per age in each cluster",
                         position = "stack")
dev.off()

pdf("/media/chang/HDD-3/chang/dapi/first_bar_sample.pdf")
SCpubr::do_BarPlot(first, group.by = "Sample", 
                         split.by = "clusters",
                         plot.title = "Number of cells per sample in each cluster",
                         position = "stack")
dev.off()

pdf("/media/chang/HDD-3/chang/dapi/first_box_umi.pdf", width = 10)
SCpubr::do_BoxPlot(sample = first, feature = "nCount_RNA") +SCpubr::do_BoxPlot(sample = first, feature = "nCount_RNA", group.by = "Sample") & ylim(500,5000)
dev.off()

pdf("/media/chang/HDD-3/chang/dapi/first_box_mt.pdf", width = 10)
SCpubr::do_BoxPlot(sample = first, feature = "percent.mt") +SCpubr::do_BoxPlot(sample = first, feature = "percent.mt", group.by = "Sample") & ylim(0,10)
dev.off()

pdf("/media/chang/HDD-3/chang/dapi/first_box_doublet.pdf", width = 10)
SCpubr::do_BoxPlot(sample = first, feature = "hybrid_score") +SCpubr::do_BoxPlot(sample = first, feature = "hybrid_score", group.by = "Sample") & ylim(0,1.5)
dev.off()

pdf("/media/chang/HDD-3/chang/dapi/first_sig_all.pdf", width = 12)
FeaturePlot(first, features = uc[1:12], ncol = 4, order=T,max.cutoff = 'q98') & NoAxes() &
  scale_color_viridis()
dev.off()

pdf("/media/chang/HDD-8/chang/aparna/pdfs/first_sig_all2.pdf", width = 12)
FeaturePlot(first, features = uc[13:23], ncol = 4, order=T,max.cutoff = 'q98') & NoAxes() &
  scale_color_viridis()
dev.off()

pdf("/media/chang/HDD-8/chang/aparna/pdfs/first_cor.pdf", width=10,height=10)
DefaultAssay(first)="SCT"
SCpubr::do_CorrelationPlot(sample = first, column_names_rot = 45,
                                cell_size = 10)
dev.off()


network <- get_dorothea(organism = "human",
                                   levels = c("A", "B", "C"))
activities <- run_wmean(mat = as.matrix(first@assays[["SCT"]]@data),
                                   network = network,
                                   .source = "source",
                                   .targe = "target",
                                   .mor = "mor",
                                   times = 100,
                                   minsize = 5)
saveRDS(activities, file='first_tf_activities.rds')
activities = readRDS("/media/chang/HDD-8/chang/aparna/first_tf_activities.rds")

pdf("/media/chang/HDD-8/chang/aparna/pdfs/first_tf.pdf")
SCpubr::do_TFActivityPlot(sample = first, max.cutoff = 1.5,min.cutoff = 1.5,
                                 activities = activities,rotate_x_axis_labels = 90,
                                 n_tfs = 30)
dev.off()

network <- get_progeny(organism = "human")
activities <- run_wmean(mat = as.matrix(first@assays[["SCT"]]@data),
                                   network = network,
                                   .source = "source",
                                   .targe = "target",
                                   .mor = "weight",
                                   times = 100,
                                   minsize = 5)
saveRDS(activities, file="first_progeny_activities.rds")

activities = readRDS('/media/chang/HDD-3/chang/first_filtered_pathway.rds')
path = activities %>%
  pivot_wider(id_cols = 'source', names_from = 'condition',
              values_from = 'score') %>%
  column_to_rownames('source')
df <- t(path) %>%
  as.data.frame() %>%
  mutate(cluster = Idents(first)) %>%
  pivot_longer(cols = -cluster, names_to = "source", values_to = "score") %>%
  group_by(cluster, source) %>%
  summarise(mean = mean(score))
# Transform to wide matrix
top_acts_mat <- df %>%
  pivot_wider(id_cols = 'cluster', names_from = 'source',
              values_from = 'mean') %>%
  column_to_rownames('cluster') %>%
  as.matrix()
# Choose color palette
top_acts_mat = top_acts_mat[,!grepl("Hypoxia|p53|Trail|VEGF|JAK",colnames(top_acts_mat))]

palette_length = 100
my_color = colorRampPalette(c("Darkblue", "white","red"))(palette_length)
my_breaks <- c(seq(-2, 0, length.out=ceiling(palette_length/2) + 1),
               seq(0.05, 2, length.out=floor(palette_length/2)))
# Plot
x = pheatmap(top_acts_mat, border_color = NA, color=my_color, breaks = my_breaks) 
pdf("/media/chang/HDD-3/chang/dapi/first_new_path.pdf", heigh=6,width = 8)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()


activities2 = readRDS('/media/chang/HDD-3/chang/first_filtered_tf.rds')
tf <- activities2 %>%
  pivot_wider(id_cols = 'source', names_from = 'condition',
              values_from = 'score') %>%
  column_to_rownames('source')
# Extract activities from object as a long dataframe
df <- t(tf) %>%
  as.data.frame() %>%
  mutate(cluster = Idents(first)) %>%
  pivot_longer(cols = -cluster, names_to = "source", values_to = "score") %>%
  group_by(cluster, source) %>%
  summarise(mean = mean(score))
# Get top tfs with more variable means across clusters
n_tfs <- 80
tfs <- df %>%
  group_by(source) %>%
  summarise(std = sd(mean)) %>%
  arrange(-abs(std)) %>%
  head(n_tfs) %>%
  pull(source)
# Subset long data frame to top tfs and transform to wide matrix
top_acts_mat <- df %>%
  filter(source %in% tfs) %>%
  pivot_wider(id_cols = 'cluster', names_from = 'source',
              values_from = 'mean') %>%
  column_to_rownames('cluster') %>%
  as.matrix()
top_acts_mat = top_acts_mat[,colMeans(top_acts_mat) > 0 & colMeans(top_acts_mat) < 5]
top_acts_mat = top_acts_mat[,colnames(top_acts_mat) != "MYC"]
top_acts_mat = top_acts_mat[,!grepl("HSF|E2F",colnames(top_acts_mat))]

# Choose color palette
palette_length = 100
my_color = colorRampPalette(c("Darkblue", "white","red"))(palette_length)
my_breaks <- c(seq(-2, 0, length.out=ceiling(palette_length/2) + 1),
               seq(0.05, 5, length.out=floor(palette_length/2)))
# Plot
x = pheatmap(top_acts_mat, border_color = NA, color=my_color, breaks = my_breaks,) 

pdf("/media/chang/HDD-3/chang/dapi/first_new_tf.pdf", heigh=6,width = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()










pdf('/media/chang/HDD-8/chang/aparna/pdfs/first_pathway.pdf')
SCpubr::do_PathwayActivityPlot(sample = first, activities = activities,max.cutoff = 1,
                       min.cutoff = -1,group.by = "clusters")
dev.off()

first.markers = lMarkers(first ,only.pos = T)
saveRDS(first.markers,file="/media/chang/HDD-8/chang/aparna/first_markers.rds")

first.markers = readRDS("/media/chang/HDD-8/chang/aparna/first_markers.rds")
first.markers = first.markers[!grepl("MIR",first.markers$gene),]
first.markers = first.markers[!grepl("AC0",first.markers$gene),]
first.markers = first.markers[!grepl("AL0",first.markers$gene),]
first.markers = first.markers[!grepl("MT-",first.markers$gene),]
first.markers = first.markers[!grepl("LINC",first.markers$gene),]
first.markers = first.markers[!grepl("RPS",first.markers$gene),]
first.markers = first.markers[!grepl("RPL",first.markers$gene),]
first.markers = first.markers[!grepl("FP236",first.markers$gene),]

top5_markers <- Extract_Top_Markers(marker_dataframe = first.markers, 
                                    num_genes = 3, named_vector = FALSE,make_unique = TRUE)
top5_markers = unique(c(top5_markers,"TCF7L2", "GBX2", "LHX2", "LHX9", "LHX1", "LHX5", 
                 "SOX14", "PAX6", "OLIG3"))
pdf("/media/chang/HDD-3/chang/dapi/first_dotplot.pdf", height = 10)
Clustered_DotPlot(seurat_object = first, features = top5_markers, x_lab_rotate = 90)
dev.off()

pdf('/media/chang/HDD-8/chang/aparna/pdfs/first_feature.pdf', width = 14)
FeaturePlot(first, features = c("LUM","HES1","EYA2","LHX9","ASCL1","GAD1","ISL1","LHX1"), ncol=4,order=T,max.cutoff = 'q98') & NoAxes() & scale_color_viridis()
dev.off()
```

```{r}
second = readRDS("/media/chang/HDD-8/chang/aparna/second.rds")
second = SCTransform(second, vst.flavor='v2', assay='cleaned', variable.features.n = 2000)

VariableFeatures(second) = VariableFeatures(second)[!grepl("MT-", VariableFeatures(second))]
VariableFeatures(second) = VariableFeatures(second)[!grepl("MALAT1", VariableFeatures(second))]
VariableFeatures(second) = VariableFeatures(second)[!grepl("RPS", VariableFeatures(second))]
VariableFeatures(second) = VariableFeatures(second)[!grepl("RPL", VariableFeatures(second))]

second$cell = "Cell"
second$cell[second$orig.ident == "510_Thal"] = "Nuclei"
second$cell[second$orig.ident == "611_Thal"] = "Nuclei"
second$cell[second$orig.ident == "993_Thal"] = "Nuclei"
second$Age[second$Sample == "611"] = "GW17"

second = RunPCA(second, npcs=30)
second = RunHarmony(second, group.by.vars=c("Sample"), assay.use="SCT",
                    kmeans_init_nstart=20, kmeans_init_iter_max=100)
second = RunUMAP(second, dims=1:30, reduction='harmony')
second = FindNeighbors(second, dims=1:30, reduction='harmony')
second = FindClusters(second, algorithm=2, resolution=1)
second = FindClusters(second, algorithm=2, resolution=.8)
second = FindClusters(second, algorithm=2, resolution=.6)
second = FindClusters(second, algorithm=2, resolution=.5)
second = FindClusters(second, algorithm=2, resolution=.4)
second = FindClusters(second, algorithm=2, resolution=.3)
second = FindClusters(second, algorithm=2, resolution=.2)
second = FindClusters(second, algorithm=2, resolution=.1)

saveRDS(second, file='second.rds')
```

```{r}
second = readRDS("/media/chang/HDD-8/chang/aparna/second.rds")

second = AddModuleScore_UCell(second, features = sigs, assay = 'SCT',ncores = 16)

saveRDS(second, file="/media/chang/HDD-8/chang/aparna/second.rds")
  
markers = wilcoxauc(second, seurat_assay = "SCT")

FeaturePlot(second, features = c("GAD1","DLX2","LHX9","OLIG1","AIF1","AQP4",
                                 "MKI67","BCAS1","FOXJ1","GLI3","HOPX","RSPH1"), ncol = 4, order=T,max.cutoff = 'q98') & NoAxes() & scale_color_viridis()

second$clusters = as.character(second$SCT_snn_res.0.4)
second$clusters[second$clusters == '0'] = "GL1"
second$clusters[second$clusters == '31'] = "GL1"
second$clusters[second$clusters == '9'] = "GL2"
second$clusters[second$clusters == '7'] = "AC"
second$clusters[second$clusters == '16'] = "EP"
second$clusters[second$clusters == '12'] = "Div"
second$clusters[second$clusters == '6'] = "IPC1"
second$clusters[second$clusters == '11'] = "IPC2"
second$clusters[second$clusters == '20'] = "IPC2"
second$clusters[second$clusters == '4'] = "OPC"
second$clusters[second$clusters == '28'] = "OPC"
second$clusters[second$clusters == '21'] = "OL"
second$clusters[second$clusters == '10'] = "MG"
second$clusters[second$clusters == '19'] = "PC"
second$clusters[second$clusters == '24'] = "FB"
second$clusters[second$clusters == '23'] = "RBC"
second$clusters[second$clusters == '14'] = "EC"
second$clusters[second$clusters == "2"] = "IN1"
second$clusters[second$clusters == "27"] = "IN1"
second$clusters[second$clusters == "29"] = "IN1"
second$clusters[second$clusters == "32"] = "IN1"
second$clusters[second$clusters == '8'] = "IN2"
second$clusters[second$clusters == '18'] = "IN3"
second$clusters[second$clusters == '3'] = "IN4"
second$clusters[second$clusters == '13'] = "IN5"
second$clusters[second$clusters == '1'] = "EN1"
second$clusters[second$clusters == '25'] = "EN1"
second$clusters[second$clusters == '22'] = "EN1"
second$clusters[second$clusters == '5'] = "EN2"
second$clusters[second$clusters == '15'] = "IN6"
second$clusters[second$clusters == '26'] = "IN6"
second$clusters[second$clusters == '30'] = "IN6"
second$clusters[second$clusters == '33'] = "IN6"
second$clusters[second$clusters == '17'] = "IN7"
Idents(second) = second$clusters

DimPlot_scCustom(second, group.by = 'clusters', label=T)

saveRDS(second, file="/media/chang/HDD-8/chang/aparna/second.rds")

thal.markers = RunPrestoAll(thal,assay = "cleaned")
saveRDS(second.markers,file="/media/chang/HDD-3/chang/dapi/second_markers.rds")

second.markers = readRDS("/media/chang/HDD-8/chang/aparna/second_markers.rds")
second.markers = second.markers[!grepl("MIR",second.markers$gene),]
second.markers = second.markers[!grepl("AC0",second.markers$gene),]

markerVocalno(markers = second.markers,
              topn = 5,
              labelCol = ggsci::pal_npg()(9))

top5_markers <- Extract_Top_Markers(marker_dataframe = second.markers, 
                                    num_genes = 3, named_vector = FALSE, 
                                    make_unique = TRUE)

pdf('/media/chang/HDD-3/chang/dapi/jjdot.pdf', width = 13, height = 6)
jjDotPlot(object = thal,assay = 'SCT',ytree = F,
          gene = top5_markers,id='clusters',
          xtree = F)
dev.off()

top5_markers = c(top5_markers,"LHX9", "GAD1","LHX1","S100A6","EYA2","FOXP2","SOX2",
                 "FOXG1","HES1","P2RY12","MKI67","SLC17A6", "PTPRZ1")


first.markers = readRDS("~/first_markers.rds")
first.markers = first.markers[!grepl("RPL", first.markers$gene),]
first.markers = first.markers[!grepl("RPS", first.markers$gene),]
first.markers = first.markers[!grepl("MT-", first.markers$gene),]
first.markers = first.markers[!grepl("FP", first.markers$gene),]
first.markers = first.markers[!grepl("AC0", first.markers$gene),]
first.markers = first.markers[!grepl("AL1", first.markers$gene),]
first.markers = first.markers[!grepl("LINC", first.markers$gene),]
first.markers = first.markers[!grepl("MIR", first.markers$gene),]
first.markers = split(first.markers, first.markers$cluster)
sigs = lapply(first.markers, function(i){
  intersect(i$gene, rownames(second))[1:15]
})
do_EnrichmentHeatmap(sample = second, group.by = 'clusters',flavor = "UCell",
                     cluster_rows = T,input_gene_list = sigs, ncores = 16, 
                     max.cutoff = .16, storeRanks = T, cluster_cols = T)


pdf("/media/chang/HDD-8/chang/aparna/pdfs/second_umap_area.pdf", width = 10)
  do_DimPlot(second, group.by = "Area")
dev.off()

pdf("/media/chang/HDD-8/chang/aparna/pdfs/second_umap_clusters.pdf", width = 10)
  do_DimPlot(second, label=T)
dev.off()


pdf("/media/chang/HDD-8/chang/aparna/pdfs/second_sig_all.pdf", width = 12)
FeaturePlot(second, features = uc[1:12], ncol = 4, order=T,max.cutoff = 'q98') & NoAxes() &
  scale_color_viridis()
dev.off()

pdf("/media/chang/HDD-8/chang/aparna/pdfs/second_sig_all2.pdf", width = 12)
FeaturePlot(second, features = uc[13:23], ncol = 4, order=T,max.cutoff = 'q98') & NoAxes() &
  scale_color_viridis()
dev.off()

pdf("/media/chang/HDD-8/chang/aparna/pdfs/second_bar_area.pdf", width = 10)
do_BarPlot(second, group.by = "Area", split.by = "clusters",
                         plot.title = "Area",
                         position = "fill",
                         flip = FALSE)
dev.off()

pdf("/media/chang/HDD-8/chang/aparna/pdfs/second_bar_age.pdf", width = 10)
do_BarPlot(second, group.by = "Age", split.by = "clusters",
                         plot.title = "Age",
                         position = "fill",
                         flip = FALSE)
dev.off()

pdf("/media/chang/HDD-8/chang/aparna/pdfs/second_bar_sample.pdf", width = 10)
do_BarPlot(second, group.by = "Sample", split.by = "clusters",
                         plot.title = "Sample",
                         position = "fill",
                         flip = FALSE)
dev.off()

pdf("/media/chang/HDD-8/chang/aparna/pdfs/second_crabp1.pdf")
do_FeaturePlot(sample = second, features = "CRABP1", order = T, max.cutoff = 98,
                             plot.title = "CRABP1", reduction = "umap")
dev.off()

pdf("/media/chang/HDD-8/chang/aparna/pdfs/second_merfish_dotplot.pdf", 
    height = 13,  width = 8)
Clustered_DotPlot(seurat_object = second, features = rownames(gw19), x_lab_rotate = 90)
dev.off()

uc = colnames(second@meta.data[grepl("UCell", colnames(second@meta.data))])
names(sigs) = uc
do_EnrichmentHeatmap(sample = second, group.by = 'clusters', flavor = "UCell",
                     cluster_rows = T,input_gene_list = sigs, ncores = 16, 
                                 storeRanks = T,cluster_cols = T, max.cutoff = .16)

pdf("/media/chang/HDD-8/chang/aparna/pdfs/second_cor.pdf", height=10, width=10)
  do_CorrelationPlot(sample = second,  cell_size = 10, group.by="clusters")
dev.off()


FeaturePlot(second, features = c("TSHZ2", "LRP2", "SEMA5A", "PKIB", "CD247",
                                 "DPYD", "PENK", "TAC1", "CDH9", "CHRM3", "CALB1",
                                 "CHRM5"), ncol=4,order=T,max.cutoff = 'q98') & NoAxes() & scale_color_viridis()

FeaturePlot(second, features = c("ETV1", "KCTD8", "ITGA8", "TLL1", "INHBA", "PVALB"), 
            ncol=3,order=T,max.cutoff = 'q98') & NoAxes() & scale_color_viridis()

network <- get_progeny(organism = "human")
activities <- run_wmean(mat = as.matrix(second@assays[["SCT"]]@data),
                                   network = network,
                                   .source = "source",
                                   .targe = "target",
                                   .mor = "weight",
                                   times = 100,
                                   minsize = 5)
saveRDS(activities, file="second_progeny_activities.rds")

network2 <- get_dorothea(organism = "human",
                                   levels = c("A", "B", "C"))
second_subset1 = subset(second, cells = colnames(second)[1:46000])
second_subset2 = subset(second, cells = colnames(second)[46001:92000])
second_subset3 = subset(second, cells = colnames(second)[92001:137761])
activities2 <- run_wmean(mat = as.matrix(second_subset1@assays[["SCT"]]@data),
                                   network = network2,
                                   .source = "source",
                                   .targe = "target",
                                   .mor = "mor",
                                   times = 100,
                                   minsize = 5)
activities3 <- run_wmean(mat = as.matrix(second_subset2@assays[["SCT"]]@data),
                                   network = network2,
                                   .source = "source",
                                   .targe = "target",
                                   .mor = "mor",
                                   times = 100,
                                   minsize = 5)
activities4 <- run_wmean(mat = as.matrix(second_subset3@assays[["SCT"]]@data),
                                   network = network2,
                                   .source = "source",
                                   .targe = "target",
                                   .mor = "mor",
                                   times = 100,
                                   minsize = 5)
saveRDS(activities2, file="second_activities.rds")

activities = readRDS("/media/chang/HDD-8/chang/aparna/second_tf_activities.rds")

second$class = "Brain"
second$class[second$clusters == "PC"] = "Vasc"
second$class[second$clusters == "EC"] = "Vasc"
second$class[second$clusters == "FB"] = "Vasc"
second$class[second$clusters == "RBC"] = "Vasc"
test = subset(second, subset=class== "Brain")
activities2 = activities[activities$condition %in% colnames(test),]

pdf('/media/chang/HDD-8/chang/aparna/pdfs/second_tf.pdf')
SCpubr::do_TFActivityPlot(sample = test,max.cutoff = 2,min.cutoff = -1,rotate_x_axis_labels = 90,
                                 activities = activities2, n_tfs = 20)
dev.off()

activities = readRDS('second_progeny_activities.rds')
activities3 = activities[activities$condition %in% colnames(test),]

pdf('/media/chang/HDD-8/chang/aparna/pdfs/second_pathway.pdf')
do_PathwayActivityPlot(sample = test, activities = activities3,max.cutoff = 1.5,
                       min.cutoff = -1,group.by = "clusters")
dev.off()

area_deg = FindMarkers(second, subset.ident = "IN4", group.by = "Area", 
                       ident.1 = "dorsal_thalamus", max.cells.per.ident = 1400)
area_deg2 = FindMarkers(second, subset.ident = "IN1", group.by = "Area", 
                       ident.1 = "ventral_thalamus", max.cells.per.ident = 700)
area_deg3 = FindMarkers(second, subset.ident = "GL1", group.by = "Area", 
                       ident.1 = "dorsal_thalamus", ident.2 = "ventral_thalamus",
                       max.cells.per.ident = 1500)
area_deg4 = FindMarkers(second, subset.ident = "MG", group.by = "Area", 
                       ident.1 = "dorsal_thalamus", ident.2 = "ventral_thalamus",
                       max.cells.per.ident = 500)

pdf("/media/chang/HDD-8/chang/aparna/pdfs/second_box_umi.pdf", width = 10)
do_BoxPlot(sample = second, feature = "nCount_RNA", group.by = 'clusters') +do_BoxPlot(sample = second, feature = "nCount_RNA", group.by = "Sample") & ylim(500,5000)
dev.off()

pdf("/media/chang/HDD-8/chang/aparna/pdfs/second_box_mt.pdf", width = 10)
do_BoxPlot(sample = second, feature = "percent.mt") +do_BoxPlot(sample = second, feature = "percent.mt", group.by = "Sample") & ylim(0,10)
dev.off()

pdf("/media/chang/HDD-8/chang/aparna/pdfs/second_box_doublet.pdf", width = 10)
do_BoxPlot(sample = second, feature = "hybrid_score") +do_BoxPlot(sample = second, feature = "hybrid_score", group.by = "Sample") & ylim(0,1.5)
dev.off()

circ_data <- prepare_circlize_data(thal, scale = 0.7 )
cluster_colors<-dittoColors()[1:length(levels(thal))]
group_colors<-dittoColors()[1:length(names(table(thal$Sample)))]
area_colors <-dittoColors()[1:length(names(table(thal$Area)))]
age_colors <-dittoColors()[1:length(names(table(thal$Age)))]
###plot and save figures
#png('/media/chang/HDD-3/chang/dapi/circlize_plot.png', width = 7, height = 7, res = 1000)
#par(omi = c(0,0,0,0), mgp = c(0,0,0), mar = c(0,0,0,0), family = "D")
pdf("/media/chang/HDD-3/chang/dapi/circlize_plot.pdf", width = 6, height = 6)
plot_circlize(circ_data,do.label = T, pt.size = 0.01, col.use = cluster_colors,
              bg.color = 'white', kde2d.n = 200, repel = T, label.cex =.8)
add_track(circ_data, group = "Sample", colors = group_colors, track_num = 2) 
add_track(circ_data, group = "Area",colors = area_colors, track_num = 3) 
add_track(circ_data, group = "Age",colors = age_colors, track_num = 4) 
dev.off()

pdf("/media/chang/HDD-3/chang/dapi/dittobar_second.pdf", width = 6, height = 3)
dittoBarPlot(thal, var='Sample', group.by = "ident")+
  theme(text = element_text(size=10))
dittoBarPlot(thal, var='Age', group.by = "ident")+
  theme(text = element_text(size=10))
dittoBarPlot(thal, var='Area', group.by = "ident")+
  theme(text = element_text(size=10))
dev.off()


second.markers = readRDS("/media/chang/HDD-7/chang/aparna/second_markers.rds")
#second.markers = second.markers[grepl("EN",second.markers$cluster),]
second.markers = second.markers[!grepl("RPL",second.markers$gene),]
second.markers = second.markers[!grepl("RPS",second.markers$gene),]
second.markers = second.markers[!grepl("HSP",second.markers$gene),]

top5_markers <- Extract_Top_Markers(marker_dataframe = second.markers, 
                                    num_genes = 5, named_vector = FALSE,
    make_unique = TRUE)

genes = rownames(gw23_l1@assays$Vizgen@counts)
genes = genes[!(genes %in% c("PTPRD","ROBO1","SOX4","RORA","PTN","MDK","HES1","KCNMB2",
                             "SOX2-OT","NRCAM","NRXN3","XKR4","BRINP3","NFIA","CHRM3",
                             "NR2F1","LPP","NKAIN2","GADD45B","OLIG3","SLC26A3","PDZRN3",
                             "POU4F1","DRD2","SP8","DLX6","LHX6","PVALB","CTXN3","CRTAC1",
                             "PRKCG","BTNL9","GAD2","ZEB2","DPYD","TSHZ2","NTRK1","PAX6",
                             "SLC32A1","SST","NKX2-1","CBLN2","PLXNA1","SNCA","KIRREL3",
                             'CRH','SNCG',"NTRK1",'NEUROD2',"EN1","PAX7","LHX2","BCHE",
                             "NECAB1","NECAB2","PKIB","GBX2","GPNMB","DACH2","LAMP5",
                             "TNNT1","CCK","SEMA5A","FRMPD4","EBF1","EPHA5","LHX5",
                             "GREB1L","ADGRV1","EGFR","GABRG1","WLS","FOXD1","TAGLN",
                             "INHBA","GRIK1","TRP4C","SGCZ","NAV2","SATB2", "DCN",
                             "APOLD1","ETV1","DLX5","THSD7B","PDZRN4","GABRG3"))]
pdf("/media/chang/HDD-3/chang/dapi/dotplot.pdf", height = 10)
Clustered_DotPlot(seurat_object = thal, features = genes,x_lab_rotate = 90)
dev.off()


pdf("/media/chang/HDD-3/chang/dapi/second_jj.pdf", width = 5)
markerVocalno(markers = second.markers,
              topn = 5,
              labelCol = dittoColors())+theme(text = element_text(size=15))
dev.off()

pdf("/media/chang/HDD-3/chang/dapi/second_NTS.pdf")
FeaturePlot(thal, features = 'NTS', order=T,max.cutoff = 'q99', pt.size = .5) + scale_color_viridis()+NoAxes()
dev.off()

test = FindMarkers(thal, group.by = 'SCT_snn_res.0.8', ident.1 = 1, ident.2 = 6, max.cells.per.ident = 6000)



thal$clusters = as.character(thal$clusters)
thal$clusters[thal$clusters == "AC"] = "AC2"
thal$clusters[thal$clusters == "GL1"] = "AC1"
thal$clusters[thal$clusters == "GL2"] = "GL"
thal$clusters = as.factor(thal$clusters)

thal$cell_status[thal$Sample == 510] = "nuc"
thal$cell_status[thal$Sample == 611] = "nuc"
thal$cell_status[thal$Sample == 993] = "nuc"

test = FindMarkers(thal, ident.1 = "EN1", ident.2 = "EN2", 
                   max.cells.per.ident = 8000)
head(test[order(test$avg_log2FC, decreasing = T),],20)

Idents(thal) = thal$cell_status
test2 = FindMarkers(thal, subset.ident = "cell", group.by = "clusters",
                    ident.1 = "EN1", ident.2 = "EN2",max.cells.per.ident = 5000)
head(test2[order(test2$avg_log2FC, decreasing = T),],20)

Idents(thal) = thal$cell_status
test3 = FindMarkers(thal, subset.ident = "nuc", group.by = "clusters",
                    ident.1 = "EN1", ident.2 = "EN2",max.cells.per.ident = 1000)
head(test3[order(test3$avg_log2FC, decreasing = T),],20)

VlnPlot(thal, features = c("NTNG1",), group.by = 'clusters', assay = "cleaned", pt.size = 0)
FeaturePlot(thal, features = "NTS", order=T, max.cutoff = 'q99') + NoAxes()


Idents(thal) = thal$clusters
pdf("/media/chang/HDD-3/chang/dapi/en_vln.pdf", width = 10)
VlnPlot(subset(thal, idents=c("EN1","EN2")), group.by = 'clusters', 
        features = c("TCF7L2","CALB2","NTS","NTNG1","RNF220","FOXP2"),
        assay = 'cleaned', pt.size = 0)
dev.off()

pdf('en_markers_spatial.pdf', width = 10)
ImageFeaturePlot(gw21_labelled, features = c("TCF7L2","CALB2","NTS","NTNG1","RNF220","FOXP2"),
                 max.cutoff = 'q90', dark.background = F) & NoAxes()
ImageFeaturePlot(gw23_l1_labelled, features = c("TCF7L2","CALB2","NTS","NTNG1","RNF220","FOXP2"),
                 max.cutoff = 'q90', dark.background = F) & NoAxes()
ImageFeaturePlot(gw23_l2_labelled, features = c("TCF7L2","CALB2","NTS","NTNG1","RNF220","FOXP2"),
                 max.cutoff = 'q90', dark.background = F) & NoAxes()
ImageFeaturePlot(gw23_l3_labelled, features = c("TCF7L2","CALB2","NTS","NTNG1","RNF220","FOXP2"),
                 max.cutoff = 'q90', dark.background = F) & NoAxes()
ImageFeaturePlot(gw23_m1_labelled, features = c("TCF7L2","CALB2","NTS","NTNG1","RNF220","FOXP2"),
                 max.cutoff = 'q90', dark.background = F) & NoAxes()
ImageFeaturePlot(gw23_m2_labelled, features = c("TCF7L2","CALB2","NTS","NTNG1","RNF220","FOXP2"),
                 max.cutoff = 'q90', dark.background = F) & NoAxes()
ImageFeaturePlot(gw23_vm_labelled, features = c("TCF7L2","CALB2","NTS","NTNG1","RNF220","FOXP2"),
                 max.cutoff = 'q90', dark.background = F) & NoAxes()
ImageFeaturePlot(gw16_labelled, features = c("TCF7L2","CALB2","NTS","NTNG1","RNF220","FOXP2"),
                 max.cutoff = 'q90', dark.background = F) & NoAxes()
ImageFeaturePlot(gw16_lgn_labelled, features = c("TCF7L2","CALB2","NTS","NTNG1","RNF220","FOXP2"),
                 max.cutoff = 'q90', dark.background = F) & NoAxes()
dev.off()



pdf('in_markers_spatial.pdf', width = 10)
ImageFeaturePlot(gw21_labelled, 
                 features = c("GAD1","FOXG1","CRABP1","LHX1","PAX6","OTX2","SOX4","NPY","MEIS2"),
                 max.cutoff = 'q95', dark.background = F) & NoAxes()
ImageFeaturePlot(gw23_l1_labelled, 
                 features = c("GAD1","FOXG1","CRABP1","LHX1","PAX6","OTX2","SOX4","NPY","MEIS2"),
                 max.cutoff = 'q95', dark.background = F) & NoAxes()
ImageFeaturePlot(gw23_l2_labelled, 
                 features = c("GAD1","FOXG1","CRABP1","LHX1","PAX6","OTX2","SOX4","NPY","MEIS2"),
                 max.cutoff = 'q95', dark.background = F) & NoAxes()
ImageFeaturePlot(gw23_l3_labelled, 
                 features = c("GAD1","FOXG1","CRABP1","LHX1","PAX6","OTX2","SOX4","NPY","MEIS2"),
                 max.cutoff = 'q95', dark.background = F) & NoAxes()
ImageFeaturePlot(gw23_m1_labelled, 
                 features = c("GAD1","FOXG1","CRABP1","LHX1","PAX6","OTX2","SOX4","NPY","MEIS2"),
                 max.cutoff = 'q95', dark.background = F) & NoAxes()
ImageFeaturePlot(gw23_m2_labelled, 
                 features = c("GAD1","FOXG1","CRABP1","LHX1","PAX6","OTX2","SOX4","NPY","MEIS2"),
                 max.cutoff = 'q95', dark.background = F) & NoAxes()
ImageFeaturePlot(gw23_vm_labelled, 
                 features = c("GAD1","FOXG1","CRABP1","LHX1","PAX6","OTX2","SOX4","NPY","MEIS2"),
                 max.cutoff = 'q95', dark.background = F) & NoAxes()
ImageFeaturePlot(gw16_labelled, 
                 features = c("GAD1","FOXG1","CRABP1","LHX1","PAX6","OTX2","SOX4","NPY","MEIS2"),
                 max.cutoff = 'q95', dark.background = F) & NoAxes()
ImageFeaturePlot(gw16_lgn_labelled, 
                 features = c("GAD1","FOXG1","CRABP1","LHX1","PAX6","OTX2","SOX4","NPY","MEIS2"),
                 max.cutoff = 'q95', dark.background = F) & NoAxes()
dev.off()
```

```{r}
mouse = readRDS("/media/chang/HDD-3/chang/mouse_thalamus/local.rds")
mouse = subset(mouse, subset=knockout == "Control")
cells = colnames(mouse)[!is.na(mouse$annotation)]
mouse = subset(mouse, cells = cells)
cells = colnames(mouse)[mouse$annotation != "Erythrocytes"]
mouse = subset(mouse, cells = cells)

genes = orthologs(genes = rownames(mouse), species = "mouse", human = FALSE)

mouse.mtx = mouse@assays$RNA@counts[genes$ensembl,]
rownames(mouse.mtx) = genes$human_symbol
mouse.mtx = mouse.mtx[!is.na(rownames(mouse.mtx)),]
mouse.mtx = CreateSeuratObject(mouse.mtx, meta.data = mouse@meta.data)
mouse = mouse.mtx
rm(mouse.mtx);gc();
mouse = SCTransform(mouse, vst.flavor='v2')
mouse = RunPCA(mouse, npcs=30)
mouse = RunHarmony(mouse, group.by.vars = "sample", assay.use = "SCT")
mouse = RunUMAP(mouse, dims=1:30, reduction='harmony', return.model = T)
DimPlot(mouse,  cols=dittoColors(), group.by='annotation', label=T) & NoAxes()
saveRDS(mouse, file='/media/chang/HDD-3/chang/mouse2.rds')

anchors <- FindTransferAnchors(
  reference = mouse,
  query = thal,
  recompute.residuals = T,
  normalization.method = "SCT",  ## SCT
  query.assay = 'SCT', ##
  reference.reduction = "harmony",
  reference.assay = "SCT", ## SCT
  features = VariableFeatures(thal),
  dims = 1:30
)
thal <- MapQuery(anchorset = anchors,
  query = thal,
  reference = mouse,
  refdata = list(celltype.l1 = "annotation"),
  reference.reduction = "harmony",
  reduction.model = "umap")
gc()
thal_conf = subset(thal, subset=predicted.celltype.l1.score > .5)
Idents(mouse) = mouse$annotation

pdf("/media/chang/HDD-3/chang/dapi/mouse_ref.pdf", width = 10)
DimPlot(mouse, label = F, cols = dittoColors()) + NoAxes()
DimPlot(thal_conf, cols=dittoColors(),reduction = 'ref.umap', 
          group.by = "clusters", label=F) +NoAxes()
dev.off()

Idents(thal_conf) = thal_conf$predicted.celltype.l1
thal_conf = subset(thal_conf, idents=c("Vascular leptomeningial cells",
                                       "Vascular endothelial cells",
                                       "Subcommissural organ",
                                       "Hypothalamus",
                                       "MB"), invert=T)
pdf('/media/chang/HDD-3/chang/dapi/mouse_bar.pdf', width = 10, height = 5)
dittoBarPlot(thal_conf, var='clusters', group.by = "predicted.celltype.l1")+NoLegend()+
  dittoBarPlot(thal_conf, var='clusters', group.by = "predicted.celltype.l1", 
               scale = 'count') + NoLegend()
dev.off()



anchors <- FindTransferAnchors(
  reference = mouse,
  query = first,
  recompute.residuals = T,
  normalization.method = "SCT",  ## SCT
  query.assay = 'SCT', ##
  reference.reduction = "harmony",
  reference.assay = "SCT", ## SCT
  features = VariableFeatures(first),
  dims = 1:30
)
first <- MapQuery(anchorset = anchors,
  query = first,
  reference = mouse,
  refdata = list(celltype.l1 = "annotation"),
  reference.reduction = "harmony",
  reduction.model = "umap")
gc()
first_conf = subset(first, subset=predicted.celltype.l1.score > .5)

Idents(first_conf) = first_conf$predicted.celltype.l1
first_conf = subset(first_conf, idents=c("Vascular leptomeningial cells",
                                       "Vascular endothelial cells",
                                       "Subcommissural organ",
                                       "Hypothalamus","OPCs","Astrocytes",
                                       "Microglia","MB"), invert=T)

pdf("/media/chang/HDD-3/chang/dapi/mouse_first_ref.pdf", width = 10)
DimPlot(mouse, label = F, cols = dittoColors()) + NoAxes()
DimPlot(first_conf, cols=dittoColors(),reduction = 'ref.umap', 
          group.by = "clusters", label=F, pt.size = 1) +NoAxes()
dev.off()

pdf('/media/chang/HDD-3/chang/dapi/mouse_first_bar.pdf', width = 10, height = 5)
dittoBarPlot(first_conf, var='clusters', group.by = "predicted.celltype.l1")+NoLegend()+
  dittoBarPlot(first_conf, var='clusters', group.by = "predicted.celltype.l1", 
               scale = 'count') + NoLegend()
dev.off()


library(babelgene)

thalamoseq = read.csv("/media/chang/HDD-3/chang/GSE133912_thal_singlecell_counts.csv",
                      row.names = 1)
thalamoseq.meta = read.csv("/media/chang/HDD-3/chang/GSE133912_thal_singlecell_metadata.csv",
                      row.names = 1)
thalamoseq = t(thalamoseq)
genes = orthologs(genes = rownames(thalamoseq), species = "mouse", human = FALSE)
thalamoseq = thalamoseq[genes$symbol,]
rownames(thalamoseq) = genes$human_symbol
thalamoseq = thalamoseq[!is.na(rownames(thalamoseq)),]
rownames(thalamoseq) = make.unique(rownames(thalamoseq))
thalamoseq = CreateSeuratObject(thalamoseq, meta.data = thalamoseq.meta)
thalamoseq = SCTransform(thalamoseq, vst.flavor='v2')
thalamoseq = RunPCA(thalamoseq)
thalamoseq = RunUMAP(thalamoseq, dims=1:20)
Idents(thalamoseq) = thalamoseq$Projection
thalamoseq.markers = RunPrestoAll(thalamoseq, assay = 'SCT')

thalamoseq.markers %>%
    group_by(cluster) %>%
    top_n(n = 50, wt = avg_log2FC) -> top10
top10.uc = list()
top10.uc$Auditory = top10$gene[top10$cluster=="Auditory"]
top10.uc$Motor = top10$gene[top10$cluster=="Motor"]
top10.uc$PFC = top10$gene[top10$cluster=="Prefrontal"]
top10.uc$SS = top10$gene[top10$cluster=="Somatosensory"]
top10.uc$Visual = top10$gene[top10$cluster=="Visual"]

thal = AddModuleScore_UCell(thal, features = top10.uc,assay = "cleaned", ncores = 16)

VlnPlot(subset(thal, idents=c("EN1","EN2","EN3","IN1","IN2","IN3","IN4","IN5")), 
        ncol = 3, pt.size= 0,cols=dittoColors(),features =
          c("Auditory_UCell","Motor_UCell","PFC_UCell","SS_UCell","Visual_UCell"))

pdf("/media/chang/HDD-3/chang/dapi/proj.pdf", width = 8, height = 4)
VlnPlot(subset(thal, idents=c("EN1","EN2","EN3","IN1","IN2","IN3","IN4","IN5")), 
        ncol = 3, pt.size= 0,cols=dittoColors(),features =
          c("Auditory_UCell","Motor_UCell","PFC_UCell","SS_UCell","Visual_UCell")) 
dev.off()
# Mouse
genes = orthologs(genes = rownames(mouse2), species = "mouse", human = FALSE)

mouse2.mtx = mouse2@assays$RNA@counts[genes$ensembl,]
rownames(mouse2.mtx) = genes$human_symbol
mouse2.mtx = mouse2.mtx[!is.na(rownames(mouse2.mtx)),]
mouse2.mtx = CreateSeuratObject(mouse2.mtx, meta.data = mouse2@meta.data)
mouse2 = mouse2.mtx
rm(mouse2.mtx);gc();

mouse1.mtx = mouse1@assays$RNA@counts[genes$ensembl,]
rownames(mouse1.mtx) = genes$human_symbol
mouse1.mtx = mouse1.mtx[!is.na(rownames(mouse1.mtx)),]
mouse1.mtx = CreateSeuratObject(mouse1.mtx, meta.data = mouse1@meta.data)
mouse1 = mouse1.mtx
rm(mouse1.mtx);gc();

Idents(mouse2) = mouse2$annotation
Idents(mouse1) = mouse1$annotation

mouse2 = SCTransform(mouse2, vst.flavor='v2')
mouse1 = SCTransform(mouse1, vst.flavor='v2')
gc()

thal = readRDS("/media/chang/HDD-3/chang/thal.rds")
thal = SCTransform(thal, vst.flavor = "v2", assay = 'cleaned')
thal <- RunHarmony(object = thal,
                              assay.use = "SCT",
                              reduction = "pca",
                              dims.use = 1:30,
                              group.by.vars = c("Sample","method"),
                              plot_convergence = TRUE)

anchors <- FindTransferAnchors(
  reference = thal,
  query = mouse2,
  recompute.residuals = T,
  normalization.method = "LogNormalize",  ## SCT
  query.assay = 'RNA', ##
  reference.reduction = "pca",
  reference.assay = "cleaned", ## SCT
  features = VariableFeatures(thal),
  dims = 1:30
)

mouse2 <- MapQuery(anchorset = anchors,
  query = mouse2,
  reference = thal,
  refdata = list(celltype.l1 = "clusters"),
  reference.reduction = "harmony",
  reduction.model = "umap")
gc()

mouse2_conf = subset(mouse2, subset=predicted.celltype.l1.score > .5)

dittoBarPlot(mouse2_conf, var='predicted.celltype.l1', group.by = "annotation")
dittoBarPlot(mouse2_conf, var='annotation', group.by = "predicted.celltype.l1")

DimPlot(thal, label = T, cols = dittoColors()) +
  DimPlot(mouse2_conf, cols=dittoColors(),reduction = 'ref.umap', 
          group.by = "predicted.celltype.l1", label=T) & NoAxes()

dittoBarPlot(mouse2_conf, var='annotation', group.by = "predicted.celltype.l1")+NoLegend()+
  dittoBarPlot(mouse2_conf, var='annotation', group.by = "predicted.celltype.l1", 
               scale = 'count')

pdf('/media/chang/HDD-3/chang/dapi/second_mouse.pdf', width = 12)
DimPlot(thal, label = F, cols = dittoColors()) +
  DimPlot(mouse2_conf, cols=dittoColors(),reduction = 'ref.umap', 
          group.by = "predicted.celltype.l1", label=F) & NoAxes()
dev.off()

pdf('/media/chang/HDD-3/chang/dapi/second_mouse_bar.pdf', width = 18, height = 5)
dittoBarPlot(mouse2_conf, var='annotation', group.by = "predicted.celltype.l1")+
dittoBarPlot(mouse2_conf, var='annotation', group.by = "predicted.celltype.l1",
            scale='count') & theme(text = element_text(size=12))
dev.off()

dittoBarPlot(mouse2_conf, var='annotation', group.by = "predicted.celltype.l1",
            scale='count') & theme(text = element_text(size=12))

thal$color = "grey"
pdf('/media/chang/HDD-3/chang/dapi/second_bar_grey.pdf', height = 6, width = 6)
dittoBarPlot(thal, var='color', group.by = "clusters",colors = "grey",
            scale='count') & theme(text = element_text(size=12))
dev.off()

first$color = "grey"
pdf('/media/chang/HDD-3/chang/dapi/second_bar_grey.pdf')
dittoBarPlot(first, var='color', group.by = "clusters",colors = "grey",
            scale='count') & theme(text = element_text(size=12))
dev.off()


Idents(mouse2_conf) = mouse2_conf$predicted.celltype.l1
pdf("/media/chang/HDD-3/chang/dapi/mouse2_en_vln.pdf", width = 10)
VlnPlot(subset(mouse2_conf, idents=c("EN1","EN2")),
        features = c("TCF7L2","CALB2","NTS","NTNG1","RNF220","FOXP2"),
        assay = 'RNA', pt.size = 0)
dev.off()

pdf("/media/chang/HDD-3/chang/dapi/mouse2_in_vln.pdf", width = 10)
VlnPlot(subset(mouse2_conf, idents=c("IN1","IN2","IN3","IN4","IN5","IN6","IN7")), features = c("GAD1","OTX2","SOX14","CRABP1","FOXG1","NRG1"), 
        pt.size = 0, group.by = "predicted.celltype.l1")
dev.off()

govek1 = readLines("/media/chang/HDD-3/chang/govek1.txt")
govek2 = readLines("/media/chang/HDD-3/chang/govek2.txt")
genes1 = orthologs(genes = govek1, species = "mouse", human = FALSE)
genes2 = orthologs(genes = govek2, species = "mouse", human = FALSE)
govek = list(EN1=genes1$human_symbol, EN2=genes2$human_symbol)
thal = AddModuleScore_UCell(thal, features = govek,assay = "cleaned", ncores = 16)
VlnPlot(subset(thal, idents=c("EN1","EN2")), features=c("EN1_UCell","EN2_UCell"),
        cols=dittoColors())

FeaturePlot(subset(thal, idents=c("EN1","EN2")), 
            features = c("CALB2","SOX2","FOXP2",'CADM1'), 
            order=T,max.cutoff = 'q98') & NoAxes()
Nebulosa::plot_density(subset(thal, idents=c("EN1","EN2")), 
features = c("CALB2","SOX2","FOXP2",'CADM1')) & NoAxes()

first = RunHarmony(first, group.by.vars='Sample', assay.use = "SCT")
first = RunUMAP(first, dims=1:20, reduction='harmony', return.model = T)

anchors2 <- FindTransferAnchors(
  reference = first,
  query = mouse1,
  recompute.residuals = T,
  normalization.method = "SCT",  ## SCT
  query.assay = 'SCT', ##
  reference.reduction = "harmony",
  reference.assay = "SCT", ## SCT
  features = VariableFeatures(first),
  dims = 1:20
)
mouse1 <- MapQuery(anchorset = anchors2,
  query = mouse1,
  reference = first,
  refdata = list(celltype.l1 = "clusters"),
  reference.reduction = "harmony",
  reduction.model = "umap")
gc()

mouse1_conf = subset(mouse1, subset=predicted.celltype.l1.score > .5)

dittoBarPlot(mouse1_conf, var='predicted.celltype.l1', group.by = "annotation")
dittoBarPlot(mouse1_conf, var='annotation', group.by = "predicted.celltype.l1")

pdf('/media/chang/HDD-3/chang/dapi/first_mouse_bar.pdf', width = 10)
dittoBarPlot(mouse1_conf, var='annotation', group.by = "predicted.celltype.l1")+
  theme(text = element_text(size=15))
dittoBarPlot(mouse1_conf, var='annotation', group.by = "predicted.celltype.l1",
            scale='count') + theme(text = element_text(size=15))
dev.off()

pdf('/media/chang/HDD-3/chang/dapi/first_mouse.pdf', width = 12)
DimPlot(first, label = F, cols = dittoColors()) +
  DimPlot(mouse1_conf, cols=dittoColors(),reduction = 'ref.umap', 
          group.by = "predicted.celltype.l1", label=F) & NoAxes()
dev.off()

genes = orthologs(genes = rownames(mouse2), species = "mouse", human = FALSE)

jab = list()
jab$HO =  unique(orthologs(readLines("/media/chang/HDD-3/chang/ho.txt"), 
                          species = "mouse", human = FALSE)$human_symbol)
jab$FO = unique(orthologs(readLines("/media/chang/HDD-3/chang/fo.txt"), 
                          species = "mouse", human = FALSE)$human_symbol)
jab$Sensory = unique(orthologs(readLines("/media/chang/HDD-3/chang/sens.txt"), 
                          species = "mouse", human = FALSE)$human_symbol)
jab$Visual = unique(orthologs(readLines("/media/chang/HDD-3/chang/visual.txt"), 
                          species = "mouse", human = FALSE)$human_symbol)
thal = AddModuleScore_UCell(thal, features = jab,assay = "SCT", ncores = 16)



thalamoseq.markers = readxl::read_xlsx("/media/chang/HDD-3/chang/sc_markers.xlsx",
                                       sheet=3)
thm = list()
thm$PFC = unique(orthologs(c(thalamoseq.markers$gene[thalamoseq.markers$cluster == "cluster_9"],
            thalamoseq.markers$gene[thalamoseq.markers$cluster == "cluster_7"]),
       species = "mouse", human = FALSE)$human_symbol)
thm$V1 = unique(orthologs(c(thalamoseq.markers$gene[thalamoseq.markers$cluster == "cluster_3"],
                            thalamoseq.markers$gene[thalamoseq.markers$cluster == "cluster_6"]),
       species = "mouse", human = FALSE)$human_symbol)
thm$A1 = unique(orthologs(c(thalamoseq.markers$gene[thalamoseq.markers$cluster == "cluster_4"],
                            thalamoseq.markers$gene[thalamoseq.markers$cluster == "cluster_8"]),
       species = "mouse", human = FALSE)$human_symbol)
thm$M1_S1 = unique(orthologs(c(thalamoseq.markers$gene[thalamoseq.markers$cluster == "cluster_1"],
                            thalamoseq.markers$gene[thalamoseq.markers$cluster == "cluster_2"],
                            thalamoseq.markers$gene[thalamoseq.markers$cluster == "cluster_4"]),
       species = "mouse", human = FALSE)$human_symbol)
thal = AddModuleScore_UCell(thal, features = thm,assay = "cleaned", ncores = 16)

VlnPlot(subset(thal, idents=c("EN1","EN2","EN3")), features=c("PFC_UCell","V1_UCell",
        "A1_UCell","M1_S1_UCell"),cols=dittoColors(), pt.size=0, ncol = 2)
VlnPlot(subset(thal, idents=c("EN1","EN2","EN3")), 
        ncol = 3, pt.size= 0,cols=dittoColors(),features =c("Primary_UCell",
                                                            "Secondary_UCell",
                                                            "Tertiary_UCell",
                                                            "AD_UCell","RE_UCell"))
VlnPlot(subset(thal, idents=c("EN1","EN2")), features=c("HO_UCell","FO_UCell",
        "Sensory_UCell","Visual_UCell"),cols=dittoColors(), pt.size=0, ncol = 2)


pdf("/media/chang/HDD-3/chang/dapi/ucell_all.pdf", height = 6, width = 7)
VlnPlot(subset(thal, idents=c("EN1","EN2")), features=c("HO_UCell","FO_UCell",
        "Sensory_UCell","Visual_UCell", "PFC_UCell","V1_UCell","A1_UCell","M1_S1_UCell",
        "Primary_UCell", "Secondary_UCell", "Tertiary_UCell"),
        cols=dittoColors(), pt.size=0, ncol = 4)
dev.off()
```

```{r}
library(decoupleR)

net <- get_collectri(organism='human', split_complexes=FALSE)

mat <- as.matrix(first@assays$cleaned@data)

# Run ulm
acts <- run_ulm(mat=mat, net=net, .source='source', .target='target',
                .mor='mor', minsize = 5)
```

```{r}
genes = intersect(VariableFeatures(thal), VariableFeatures(first))

first.mtx = AverageExpression(first, features = genes, group.by = 'clusters',
                              assays = 'cleaned', slot = 'data')
second.mtx = AverageExpression(thal, features = genes, group.by = 'clusters',
                               assays = 'cleaned', slot = 'data')

cor.matrix = cor(as.matrix(first.mtx$cleaned), as.matrix(second.mtx$cleaned))

pheatmap::pheatmap(t(cor.matrix), filename = "first_second_cor.pdf",fontsize = 8,
                   width = 5, height = 7)

pdf("/media/chang/HDD-3/chang/dapi/first_second_cor.pdf", width = 5, height = 8)
pheatmap::pheatmap(t(cor.matrix))
dev.off()

thalamoseq.meta = read.csv("/media/chang/HDD-3/chang/GSE133911_thal_nuclei_metadata.csv",
                      row.names = 1)
thalamoseq = read.csv("/media/chang/HDD-3/chang/GSE133911_thal_nuclei_counts.csv",
                      row.names = 1, header=F)
colnames(thalamoseq) = thalamoseq[2,]
thalamoseq = thalamoseq[3:122,]

genes = orthologs(genes = colnames(thalamoseq), species = "mouse", human = FALSE)
thalamoseq = thalamoseq[,genes$symbol]
colnames(thalamoseq) = genes$human_symbol
thalamoseq = thalamoseq[!is.na(colnames(thalamoseq)),]
colnames(thalamoseq) = make.unique(colnames(thalamoseq))

thalamoseq=thalamoseq %>%  mutate(across(where(is.character), str_trim))
thalamoseq = thalamoseq[1:120,]
thalamoseq = t(thalamoseq)
thalamoseq = as.matrix(thalamoseq)
class(thalamoseq) <- "numeric"
thalamoseq = CreateSeuratObject(thalamoseq, meta.data = thalamoseq.meta)
thalamoseq = SCTransform(thalamoseq, vst.flavor='v2')
thalamoseq = RunPCA(thalamoseq)
thalamoseq = RunUMAP(thalamoseq, dims=1:10)
Idents(thalamoseq) = thalamoseq$region
DimPlot(thalamoseq ,cols=dittoColors(), label=T, pt.size = 4, reduction = 'pca')

thalamoseq$Area = "Primary"
thalamoseq$Area[grepl("VPMpc|MD|LP|PO|AM|IAD|VA|VM",thalamoseq$region)] = "Secondary"
thalamoseq$Area[grepl("CL|PF|CM|PCN|SPA|IMD|PVT",thalamoseq$region)] = "Tertiary"
thalamoseq$Area[thalamoseq$region == "AD"] = "AD"
thalamoseq$Area[thalamoseq$region == "RE"] = "RE"

thalamoseq$Area = as.factor(thalamoseq$Area)
Idents(thalamoseq) = thalamoseq$Area
levels(thalamoseq) = c("Primary","Secondary","Tertiary","AD","RE")
thalamoseq.markers = RunPrestoAll(thalamoseq, assay = 'SCT')
thalamoseq.markers = thalamoseq.markers[thalamoseq.markers$p_val_adj < .1,]
thalamoseq.markers = thalamoseq.markers[thalamoseq.markers$cluster != "AD",]
thalamoseq.markers = thalamoseq.markers[thalamoseq.markers$cluster != "RE",]
thalamoseq.markers %>%
    group_by(cluster) %>%
    top_n(n = 50, wt = avg_log2FC) -> top10
top10 = data.frame(top10)
top10.df <- split(top10,top10$cluster)
top10.df = lapply(top10.df, function(i) unlist(lapply(strsplit(i$gene, "\\."), 
                  function(j) j[[1]])))
top10.df = top10.df[1:3]
thal = AddModuleScore_UCell(thal, features = top10.df,assay = "cleaned", ncores = 16)

VlnPlot(subset(thal, idents=c("EN1","EN2","EN3")), 
        ncol = 3, pt.size= 0,cols=dittoColors(),features =c("Primary_UCell",
                                                            "Secondary_UCell",
                                                            "Tertiary_UCell"))

pdf('/media/chang/HDD-3/chang/dapi/density.pdf', width = 12, height = 10)
plot_density(subset(thal, idents=c("EN1","EN2","EN3")), features = c("SLC17A6", "LHX9", "GBX2", "FOXP2", "SOX2", "CADM1", "PENK","CBLN2","CRTAC1"), reduction = 'umap') & NoAxes()
dev.off()

genes = c("SLC17A6", "LHX9", "GBX2", "FOXP2", "SOX2", "CADM1", "PENK","CBLN2","CRTAC1",
                                "GAD1", "LHX1", "LHX5", "SST", "PVALB", "ISL1", 
                                "INHBA", "FOXG1", "CRABP1", "DLX5", "SOX14", "OTX2", 
                                "TLL1","NEUROD1", "NEUROD4", "NEUROG1", "NEUROG2", 
                                "EYA2", "DACH2","OLIG1", "OLIG2", "HES6", "ASCL1", 
                                "DLL1", "PDGFRA","PTN","GFAP","AQP4","GJA1", "TNC",
                                "AGT","SPARCL1","GADD45B","ID3","LGR6","WFDC1","PLA2G5",
                                "MKI67","FOXJ1","CLDN5","DCN","HIGD1B","AIF1")

pdf('/media/chang/HDD-3/chang/dapi/density.pdf', width = 12, height = 8)
plot_density(thal, features =genes[1:25], 
             reduction = 'umap') & NoAxes()
plot_density(thal, features =genes[26:50], 
             reduction = 'umap') & NoAxes()
dev.off()
```

```{r}
first.markers = RunPrestoAll(first, assay = 'SCT')
first.markers = first.markers[!grepl("^AC",first.markers$gene),]
first.markers = first.markers[!grepl("^AL",first.markers$gene),]
first.markers = first.markers[!grepl("^MIR",first.markers$gene),]
top5_markers <- Extract_Top_Markers(marker_dataframe = first.markers, 
                                    num_genes = 4, named_vector = FALSE, 
                                    make_unique = TRUE)
top5_markers = unique(c("TCF7L2", "GBX2", "LHX2", "LHX9",top5_markers, 
                 "SOX14"))
top5_markers[14] = "LHX1"
top5_markers[31] = "LHX5"
top5_markers[11] = "PAX6"
top5_markers[28] = "OLIG3"
top5_markers[33] = "RSPO3"
top5_markers[6] = "FOXP2"
top5_markers = c(top5_markers[1:18],"SOX14",top5_markers[19:41])
top5_markers[23] = "EYA2"
top5_markers = c(top5_markers[1:34],"HES1",top5_markers[35:42])

pdf('/media/chang/HDD-3/chang/dapi/first_jjdot.pdf', width = 11, height = 8)
jjDotPlot(object = first,assay = 'SCT',ytree = F,
          gene = top5_markers,id='clusters',
          xtree = F)
dev.off()
```


```{r}
group <- structure(thal_n$class,names=thal_n$clusters) # create the cell class for the subclasses, used for plot 
thal_n = subset(thal, idents=c("EN1","EN2","IN1","IN2","IN3","IN4","IN5","IN6"))
thal_n@meta.data$class = "IN"
thal_n$class[grepl("EN",thal_n$clusters)] = "EN"
# creat NeuronChat object; choose the database 'mouse' for mouse data; 'human' for human data
# note that the first parameter should be a numeric matrix with row gene and column cell
nc <- createNeuronChat(thal_n@assays$cleaned@data,thal_n@meta.data,
                       DB='human', group.by = thal_n$clusters)


# M is for the permutation test; typically ~4 mins when M=100, depending on the dataset size and the number of cell groups
# setting M=10 to get a quick start
nc <- run_NeuronChat(nc,M=100)
#> Time difference of 5.181635 mins
# the the communication networks for individual interaction pairs are stored in slot 'net'
# aggregate the communication networks over all interaction pairs, method can be 'weight', 'count' and so on
net_aggregated_x <- net_aggregation(nc@net,method = 'weight')




par(mfrow=c(1,2))
# Visualization, circle plot, for the aggregated network
netVisual_circle_neuron(nc,group=group,vertex.label.cex = 1)
# Visualization, chordDiagram, for the aggregated network; also using cellchat function netVisual_chord_cell_internal(net_aggregated_x, group = group,lab.cex=1)
netVisual_chord_neuron(nc,method = 'weight',group=group,lab.cex = 1)

heatmap_aggregated(nc, method='weight',group=group)

lig_tar_heatmap(nc,interaction_name='PENK_OPRM1',width.vector=c(0.38,0.35,0.27))

g1 <- rankNet_Neuron(nc,slot.name = "net",measure = c("weight"),mode='single',font.size = 5) 
g2 <- rankNet_Neuron(nc,slot.name = "net",measure = c("count"),mode='single',font.size = 5)
g1+g2

x<- identifyCommunicationPatterns_Neuron(nc, slot.name = "net", pattern = c("outgoing"), k=4,height = 18)
x<- identifyCommunicationPatterns_Neuron(nc, slot.name = "net", pattern = c("incoming"), k=4,height = 18)
```
