---
title: "TRACE"
output: html_notebook
---

```{r}
seuratToH5AD <- function(seuratObj, h5ad_output, pca=TRUE, umap=TRUE){
  Sys.setenv(RETICULATE_PYTHON = "/home/chang/miniconda3/envs/venv/bin/python")
  library(reticulate)
  library(Matrix)
  writeMM(t(seuratObj@assays$RNA@counts), file='combined.mtx')
  write.csv(rownames(seuratObj@assays$RNA@counts), file = "genes.csv", row.names = FALSE)
  if(umap == TRUE){
  	write.csv(seuratObj@reductions$umap@cell.embeddings, file = "umap.csv", row.names = FALSE)
  }
  if(pca == TRUE){
	  write.csv(seuratObj@reductions$pca@cell.embeddings, file = "pca.csv", row.names = FALSE)
  }
  write.csv(colnames(seuratObj@assays$RNA@counts), file = "cells.csv", row.names = FALSE)
  write.csv(seuratObj@meta.data, file = "meta.csv", row.names = FALSE)
  source_python('/home/chang/build_no_spliced.py')
  build(h5ad_output, pca = pca, umap = umap)
  file.remove('combined.mtx')
  file.remove('genes.csv')
  file.remove('cells.csv')
  file.remove('meta.csv')
  if(umap == TRUE){
  	file.remove('umap.csv')
  }
  if(pca == TRUE){
	  file.remove('pca.csv')
  }
}
```

```{r}
library(Seurat)
library(harmony)
library(GEMLI)
library(igraph)
library(scCustomize)
library(SeuratData)
library(SeuratDisk)
library(Azimuth)
library(decoupleR)
library(dittoSeq)

calls = c("~/data_dir/pilot_class.csv",
          "~/data_dir/SAM24416646_class.csv",
          "~/data_dir/SAM24416647_class.csv",
          "~/data_dir/SAM24416644_class.csv",
          "~/data_dir/SAM24416645_class.csv")
proj = c("Pilot","ADM1","ADM2","Founder1","Founder2")
h5 = c("~/data_dir/pilot_raw.h5","~/data_dir/SAM24416646_raw.h5",
       "~/data_dir/SAM24416647_raw.h5","~/data_dir/SAM24416644_raw.h5",
       "~/data_dir/SAM24416645_raw.h5")

preprocess = function(mtx, calls, proj){
  call = read.table(calls, sep=',', row.names = 1, header=T)
  seurat = CreateSeuratObject(Read10X_h5(mtx), project = proj, min.features = 1000)
  seurat[["percent.mt"]] <- PercentageFeatureSet(seurat, pattern = "^MT-")
  seurat = subset(seurat, subset=percent.mt < 25)
  
  seurat$clone = "NoCall"
  seurat$n_bcs = 0
  inter = intersect(rownames(call), colnames(seurat))
  seurat$n_bcs[inter] = call[inter,]$n_sgRNAs
  seurat$clone[inter] = call[inter,]$sgRNAs
  seurat$clone[seurat$clone == ""] = "NoCall"
  seurat
}

seurat_list = lapply(c(1:5), function(i) preprocess(h5[[i]], calls[[i]], proj[[i]]))
merged = merge(seurat_list[[1]], seurat_list[2:5])

#VlnPlot(merged, features = 'nCount_RNA', group.by = 'orig.ident')
#dittoBarPlot(merged, var='orig.ident', var='clone') + NoLegend()
```
Processing and reference mapping as well conversion to h5ad object
```{r}
merged = SCTransform(merged, vst.flavor='v2', ncells = 5000, n_genes=NULL)
merged = RunPCA(merged)
merged = RunUMAP(merged, dims=1:30)

merged <- RunAzimuth(merged, reference = "lungref")

merged2 = subset(merged, subset=n_bcs > 0)
merged2$unique_clone = paste0(merged2$orig.ident, "_", merged2$clone)


clones = table(merged2$unique_clone)
clones = clones[clones > 2]
plot(clones[order(clones)])
merged3 = subset(merged2, subset=unique_clone %in% names(clones))

merged3$clone2 = paste0(unlist(lapply(strsplit(merged3$clone, "-"), function(i) i[[2]])),
                        merged3$n_bcs)


DefaultAssay(merged3) = "SCT"
merged3 = RunUMAP(merged3, dims=1:30)
merged3 = FindNeighbors(merged3, dims=1:30)
merged3 = FindClusters(merged3, algorithm = 4)

merged3$clusters = as.character(merged3$SCT_snn_res.0.8)
merged3$clusters[merged3$clusters == 5] = "AT2_Div_1"
merged3$clusters[merged3$clusters == 6] = "AT2_Div_2"
merged3$clusters[merged3$clusters == 9] = "AT2_Div_3"
merged3$clusters[merged3$clusters == 1] = "AT2_Founder_1"
merged3$clusters[merged3$clusters == 3] = "AT2_Founder_2"
merged3$clusters[merged3$clusters == 4] = "AT2_Founder_3"
merged3$clusters[merged3$clusters == 10] = "AT2_Founder_4"
merged3$clusters[merged3$clusters == 2] = "AT2_ADM"
merged3$clusters[merged3$clusters == 8] = "Club_ADM"
merged3$clusters[merged3$clusters == 12] = "Transitional_AT2_ADM"
merged3$clusters[merged3$clusters == 7] = "AT1_ADM_1"
merged3$clusters[merged3$clusters == 11] = "AT1_ADM_2"

Idents(merged3) = merged3$clusters


DimPlot_scCustom(merged3, group.by = 'orig.ident', pt.size = 1) + ggtitle("Batch") +  
  DimPlot_scCustom(merged3,label=F, pt.size = 1, group.by = "clusters") + ggtitle("DeNovo") + 
  DimPlot_scCustom(merged3, group.by = 'predicted.ann_finest_level', pt.size = 1) & NoAxes()

merged3$time_info=0
merged3$time_info[merged3$orig.ident == "ADM1"] = 1
merged3$time_info[merged3$orig.ident == "ADM2"] = 1
merged3$Condition = "Founder"
merged3$Condition[merged3$orig.ident == "ADM1"] = "ADM"
merged3$Condition[merged3$orig.ident == "ADM2"] = "ADM"

seuratToH5AD(merged3,h5ad_output = "/home/chang/data_dir/data.h5ad",pca = TRUE,umap=TRUE)
```
TF analysis and marker gene analysis for Tracy
```{r}
net <- get_dorothea(organism='human', levels=c('A', 'B', 'C'))

mat <- as.matrix(merged3@assays$SCT@data)

# Run wmean
acts <- run_wmean(mat=mat, net=net, .source='source', .target='target',
                  .mor='mor', times = 100, minsize = 5)

merged3[['tfswmean']] <- acts %>%
  filter(statistic == 'norm_wmean') %>%
  pivot_wider(id_cols = 'source', names_from = 'condition',
              values_from = 'score') %>%
  column_to_rownames('source') %>%
  Seurat::CreateAssayObject(.)

# Change assay
DefaultAssay(object = merged3) <- "tfswmean"

# Scale the data
merged3 <- ScaleData(merged3)
merged3@assays$tfswmean@data <- merged3@assays$tfswmean@scale.data


tf.markers = FindAllMarkers(merged3, only.pos = T)

tf.markers %>%
    group_by(cluster) %>%
    top_n(n = 5, wt = avg_log2FC) -> top10
write.csv(file = "tf_markers.csv", x = tf.markers, quote=F)

DefaultAssay(merged3) = "tfswmean"
DoHeatmap(merged3, features = top10$gene) + NoLegend() + theme(text = element_text(size=12))

DefaultAssay(merged3) = "SCT"
sct.markers = FindAllMarkers(merged3, only.pos = T)
write.csv(file = "cluster_markers.csv", x = sct.markers, quote=F)

sct.markers %>%
    group_by(cluster) %>%
    top_n(n = 5, wt = avg_log2FC) -> top10

merged3 = GetResidual(merged3, features = top10$gene)
DoHeatmap(merged3, features = top10$gene, disp.min = 0, disp.max = 3) + NoLegend() + scale_fill_viridis()

FeaturePlot(merged3, features = c("KRT8","CLDN4","SFN","KRT19","SOX4"),
            max.cutoff = 'q95',  order=T, ncol = 3) & scale_color_viridis() & NoAxes()

dittoHeatmap(merged3, genes=top10$gene, annot.by = c("clusters","Condition"),
             assay = 'tfswmean', scaled.to.max = T)


```
Testing lineage rescue of barcoded cells
```{r}
gemli_list = lapply(seurat_list, function(i){
  GEMLI_items = list()
  GEMLI_items[['gene_expression']] = as.matrix(i@assays$RNA@counts)
  GEMLI_items[['barcodes']] = i$clone
  predict_lineages(GEMLI_items)
})
test = test_lineages(gemli_list[[1]], plot_results = T)

visualize_as_network(test, cutoff=70)
visualize_as_network(test, cutoff=70, ground_truth=T) 

seurat_subset = lapply(seurat_list, function(i){
  subset(i, subset=n_bcs > 0)
})
gemli_subset = lapply(seurat_subset, function(i){
  GEMLI_items = list()
  GEMLI_items[['gene_expression']] = as.matrix(i@assays$RNA@counts)
  GEMLI_items[['barcodes']] = i$clone
  predict_lineages(GEMLI_items)
})
test = test_lineages(gemli_subset[[1]], plot_results = T)
```